In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Tejas Gaikwad\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Tejas Gaikwad\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Tejas Gaikwad\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Tejas Gaikwad\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 1.2 MB/s eta 0:00:08
   --- ------------------------------------ 0.8/9.8 MB 1.2 MB/s eta 0:00:08
   ---- ----------------------------------- 1.0/9.8 MB 1.3 MB/s eta 0:00:07
   ----- ---------------------------------- 1.3/9.8 MB 1.3 MB/s eta 0:00:07
   ------- -------------------------------- 1.8/9.8 MB 1.5 MB/s eta 0:00:06
   -------- ------------------------------- 2.1/9.8 MB 1.5 MB/s eta 0:00:06
   ---------- ----------------------------- 2.6/9.8 MB 1.6 MB/s eta 0:00:05
   ----------- ---------------------------- 2.9/9.8 MB 1.6 MB/s eta 0:00:05
   ------------- -------------------------- 3.4/9.8 MB 1.7 MB/s eta 0:00:04
   -------------- ------------------------- 3.7/9.8 MB 1.7 MB/s eta 0:00:04
   ---------------- ----------------------- 3.9/9.8 MB 1.6 MB/s eta 0:00:04
   ----------------- ---------------------- 4.2/9.8 MB 1.6 MB/s eta 0:00:04
   ------------------ --------------------- 4.5/9.8 MB 1.6 MB/s eta 0:00:04
   -------------------- ------------------- 5.0/9.8 MB 1.6 MB/s eta 0:00:04
   --------------------- ------------------ 5.2/9.8 MB 1.6 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.8 MB 1.6 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.8 MB 1.6 MB/s eta 0:00:03
   ------------------------- -------------- 6.3/9.8 MB 1.6 MB/s eta 0:00:03
   --------------------------- ------------ 6.8/9.8 MB 1.6 MB/s eta 0:00:02
   ---------------------------- ----------- 7.1/9.8 MB 1.6 MB/s eta 0:00:02
   ------------------------------- -------- 7.6/9.8 MB 1.7 MB/s eta 0:00:02
   --------------------------------- ------ 8.1/9.8 MB 1.7 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.8 MB 1.8 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 1.8 MB/s  0:00:05
Installing collected packages: pandas
Successfully installed pandas-3.0.6

In [1]:
import pandas as pd
import numpy as np

In [3]:
d1 = {'e_id':[101,102,103,104,105],
      'e_name':['amol','amit','akash','avinash','atish'],
      'e_sal':[25000,17500.5,55000,82000,42200.1],
      'e_dept':['HR','HR','IT','IT','IT']}
df = pd.DataFrame(d1,index=['A','B','C','X','Y'])
df

   e_id   e_name    e_sal e_dept
A   101     amol  25000.0     HR
B   102     amit  17500.5     HR
C   103    akash  55000.0     IT
X   104  avinash  82000.0     IT
Y   105    atish  42200.1     IT

# iloc() is gives actual content of that index

In [4]:
df.iloc[3,2] #gives the value at that index

np.float64(82000.0)

In [6]:
#and we can update values also
df.iloc[3,2] = 6700
df

   e_id   e_name    e_sal e_dept
A   101     amol  25000.0     HR
B   102     amit  17500.5     HR
C   103    akash  55000.0     IT
X   104  avinash   6700.0     IT
Y   105    atish  42200.1     IT

In [7]:
df['e_sal'].mean()

np.float64(29280.120000000003)

In [9]:
df.iloc[2:,:2] #rows and column

   e_id   e_name
C   103    akash
X   104  avinash
Y   105    atish

In [10]:
print(df)

   e_id   e_name    e_sal e_dept
A   101     amol  25000.0     HR
B   102     amit  17500.5     HR
C   103    akash  55000.0     IT
X   104  avinash   6700.0     IT
Y   105    atish  42200.1     IT

# .loc() gives the row series

In [14]:
df.loc['A']

e_id          101
e_name       amol
e_sal     25000.0
e_dept         HR
Name: A, dtype: object

In [15]:
df

   e_id   e_name    e_sal e_dept
A   101     amol  25000.0     HR
B   102     amit  17500.5     HR
C   103    akash  55000.0     IT
X   104  avinash   6700.0     IT
Y   105    atish  42200.1     IT

In [18]:
df['e_dept'] == 'IT'

A    False
B    False
C     True
X     True
Y     True
Name: e_dept, dtype: bool

In [19]:
#data of employee of IT department
df[df['e_dept'] == 'IT']

   e_id   e_name    e_sal e_dept
C   103    akash  55000.0     IT
X   104  avinash   6700.0     IT
Y   105    atish  42200.1     IT

In [20]:
#we need only salary
df[df['e_dept'] == 'IT']['e_sal']

C    55000.0
X     6700.0
Y    42200.1
Name: e_sal, dtype: float64

In [21]:
#mean of salary
df[df['e_dept'] == 'IT']['e_sal'].mean()

np.float64(34633.36666666667)

#### count of employeee more than 50K salary

In [23]:
df['e_sal'] > 50000

A    False
B    False
C     True
X    False
Y    False
Name: e_sal, dtype: bool

In [24]:
sum(df['e_sal'] > 50000)

1

#### Max Salary from HR Dept

In [25]:
df['e_dept'] == 'HR'

A     True
B     True
C    False
X    False
Y    False
Name: e_dept, dtype: bool

In [26]:
df[df['e_dept'] == 'HR']['e_sal']

A    25000.0
B    17500.5
Name: e_sal, dtype: float64

In [27]:
max(df[df['e_dept'] == 'HR']['e_sal'])

25000.0

#### How many emp from "IT" dept getting less than 60K

In [28]:
df[df['e_dept'] == 'IT']['e_sal']

C    55000.0
X     6700.0
Y    42200.1
Name: e_sal, dtype: float64

In [29]:
df[df['e_dept'] == 'IT']['e_sal'] > 60000

C    False
X    False
Y    False
Name: e_sal, dtype: bool

In [30]:
sum(df[df['e_dept'] == 'IT']['e_sal'] > 60000)

0

#### Name of emp who has highest salary

In [36]:
df['e_sal'].max()

np.float64(55000.0)

In [38]:
max(df['e_sal'])

55000.0

In [39]:
df[df['e_sal'] == df['e_sal'].max()]

   e_id e_name    e_sal e_dept
C   103  akash  55000.0     IT

In [40]:
df[df['e_sal'] == df['e_sal'].max()]['e_name']

C    akash
Name: e_name, dtype: str

In [4]:
df[df['e_sal'] == df['e_sal'].max()]['e_name'].iloc[0] #if we only want the name

'avinash'

In [5]:
df[df['e_sal'] == df['e_sal'].min()]['e_name'].iloc[0]

'amit'

In [6]:
df['e_name'].min()#alphabetical order

'akash'

## Reading data from diffrent files --> Excel,sql,csv,...

In [2]:
df = pd.read_excel('stud_db.xlsx')

In [3]:
df

   Roll Name  Marks Address  Dept
0     1   qw     76    Pune     1
1     2   df     45  Mumbai     1
2     3   vc     56  Nagpur     1
3     4   bn     78    Pune     2
4     5   hj     74  Mumbai     2
5     6   yu     49  Nagpur     2
6     7   fg     68    Pune     2
7     8   tr     84  Mumbai     1

In [4]:
# 1) find avg marks from pune,mumbai,nagpur
df['Address'] == 'Pune'

0     True
1    False
2    False
3     True
4    False
5    False
6     True
7    False
Name: Address, dtype: bool

In [8]:
df[df['Address'] == 'Pune']['Marks']

0    76
3    78
6    68
Name: Marks, dtype: int64

In [9]:
df[df['Address'] == 'Pune']['Marks'].mean()

np.float64(74.0)

In [10]:
df[df['Address'] == 'Mumbai']['Marks'].mean()

np.float64(67.66666666666667)

In [11]:
df[df['Address'] == 'Nagpur']['Marks'].mean()

np.float64(52.5)

In [12]:
#2) find count of failed stdents from mumbai pass >= 50
df[df['Address'] == 'Mumbai']['Marks']

1    45
4    74
7    84
Name: Marks, dtype: int64

In [13]:
df[df['Address'] == 'Mumbai']['Marks'] <= 50

1     True
4    False
7    False
Name: Marks, dtype: bool

In [14]:
sum(df[df['Address'] == 'Mumbai']['Marks'] <= 50)

1

In [15]:
#3)find name of topper
df['Marks'].max()

np.int64(84)

In [16]:
df['Marks'].max() == df['Marks']

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
Name: Marks, dtype: bool

In [17]:
df[df['Marks'].max() == df['Marks']]

   Roll Name  Marks Address  Dept
7     8   tr     84  Mumbai     1

In [20]:
df[df['Marks'].max() == df['Marks']]['Name']

7    tr
Name: Name, dtype: str

In [21]:
df[df['Marks'].max() == df['Marks']]['Name'].iloc[0]

'tr'

In [23]:
#4)find topper marks from dept 2
df[df['Dept'] == 2]

   Roll Name  Marks Address  Dept
3     4   bn     78    Pune     2
4     5   hj     74  Mumbai     2
5     6   yu     49  Nagpur     2
6     7   fg     68    Pune     2

In [24]:
df[df['Dept'] == 2]['Marks']

3    78
4    74
5    49
6    68
Name: Marks, dtype: int64

In [39]:
df[df['Dept'] == 2]['Marks'].max()

np.int64(78)

In [26]:
print(df[df['Dept'] == 2]['Marks'].max())

78

In [4]:
#If we want to many columns so we use data in list at the end
df[df['Marks'] == df[df['Dept'] == 2]['Marks'].max()][['Name','Marks']]

  Name  Marks
3   bn     78

## Series Funtions

## 1) .unique()

In [42]:
df['Address'].unique() # Gives the unique value from data

<ArrowStringArray>
['Pune', 'Mumbai', 'Nagpur']
Length: 3, dtype: str

## 2) .nunique()

In [45]:
df['Address'].nunique() #total of unique value

3

## 3) .value_counts()

In [47]:
df['Address'].value_counts() #tells the count of unique values elements

Address
Pune      3
Mumbai    3
Nagpur    2
Name: count, dtype: int64

## 4) .appy()

In [49]:
df['Address'].apply(lambda x : x[:2]) #like we use map in list we use appy in series

0    Pu
1    Mu
2    Na
3    Pu
4    Mu
5    Na
6    Pu
7    Mu
Name: Address, dtype: str

In [51]:
df['Address'].apply(lambda x : x[0] + x[-1])

0    Pe
1    Mi
2    Nr
3    Pe
4    Mi
5    Nr
6    Pe
7    Mi
Name: Address, dtype: str

In [56]:
np.where(df['Marks'] >= 50, df['Marks'] + 5, df['Marks'] + 10)

array([81, 55, 61, 83, 79, 59, 73, 89])

In [58]:
df['Marks'].apply(lambda x : x+ 10 if x <= 50 else x + 5)

0    81
1    55
2    61
3    83
4    79
5    59
6    73
7    89
Name: Marks, dtype: int64