In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Tejas Gaikwad\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Tejas Gaikwad\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Tejas Gaikwad\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Tejas Gaikwad\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 1.2 MB/s eta 0:00:08
   --- ------------------------------------ 0.8/9.8 MB 1.2 MB/s eta 0:00:08
   ---- ----------------------------------- 1.0/9.8 MB 1.3 MB/s eta 0:00:07
   ----- ---------------------------------- 1.3/9.8 MB 1.3 MB/s eta 0:00:07
   ------- -------------------------------- 1.8/9.8 MB 1.5 MB/s eta 0:00:06
   -------- ------------------------------- 2.1/9.8 MB 1.5 MB/s eta 0:00:06
   ---------- ----------------------------- 2.6/9.8 MB 1.6 MB/s eta 0:00:05
   ----------- ---------------------------- 2.9/9.8 MB 1.6 MB/s eta 0:00:05
   ------------- -------------------------- 3.4/9.8 MB 1.7 MB/s eta 0:00:04
   -------------- ------------------------- 3.7/9.8 MB 1.7 MB/s eta 0:00:04
   ---------------- ----------------------- 3.9/9.8 MB 1.6 MB/s eta 0:00:04
   ----------------- ---------------------- 4.2/9.8 MB 1.6 MB/s eta 0:00:04
   ------------------ --------------------- 4.5/9.8 MB 1.6 MB/s eta 0:00:04
   -------------------- ------------------- 5.0/9.8 MB 1.6 MB/s eta 0:00:04
   --------------------- ------------------ 5.2/9.8 MB 1.6 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.8 MB 1.6 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.8 MB 1.6 MB/s eta 0:00:03
   ------------------------- -------------- 6.3/9.8 MB 1.6 MB/s eta 0:00:03
   --------------------------- ------------ 6.8/9.8 MB 1.6 MB/s eta 0:00:02
   ---------------------------- ----------- 7.1/9.8 MB 1.6 MB/s eta 0:00:02
   ------------------------------- -------- 7.6/9.8 MB 1.7 MB/s eta 0:00:02
   --------------------------------- ------ 8.1/9.8 MB 1.7 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.8 MB 1.8 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 1.8 MB/s  0:00:05
Installing collected packages: pandas
Successfully installed pandas-3.0.6

In [2]:
import pandas as pd

In [3]:
d1 = {'e_id':[101,102,103,104,105],
      'e_name':['amol','amit','akash','avinash','atish'],
      'e_sal':[25000,17500.5,55000,82000,42200.1],
      'e_dept':['HR','HR','IT','IT','IT']}
df = pd.DataFrame(d1,index=['A','B','C','X','Y'])
df

   e_id   e_name    e_sal e_dept
A   101     amol  25000.0     HR
B   102     amit  17500.5     HR
C   103    akash  55000.0     IT
X   104  avinash  82000.0     IT
Y   105    atish  42200.1     IT

# iloc() is gives actual content of that index

In [4]:
df.iloc[3,2] #gives the value at that index

np.float64(82000.0)

In [6]:
#and we can update values also
df.iloc[3,2] = 6700
df

   e_id   e_name    e_sal e_dept
A   101     amol  25000.0     HR
B   102     amit  17500.5     HR
C   103    akash  55000.0     IT
X   104  avinash   6700.0     IT
Y   105    atish  42200.1     IT

In [7]:
df['e_sal'].mean()

np.float64(29280.120000000003)

In [9]:
df.iloc[2:,:2] #rows and column

   e_id   e_name
C   103    akash
X   104  avinash
Y   105    atish

In [10]:
print(df)

   e_id   e_name    e_sal e_dept
A   101     amol  25000.0     HR
B   102     amit  17500.5     HR
C   103    akash  55000.0     IT
X   104  avinash   6700.0     IT
Y   105    atish  42200.1     IT

# .loc() gives the row series

In [14]:
df.loc['A']

e_id          101
e_name       amol
e_sal     25000.0
e_dept         HR
Name: A, dtype: object

In [15]:
df

   e_id   e_name    e_sal e_dept
A   101     amol  25000.0     HR
B   102     amit  17500.5     HR
C   103    akash  55000.0     IT
X   104  avinash   6700.0     IT
Y   105    atish  42200.1     IT

In [18]:
df['e_dept'] == 'IT'

A    False
B    False
C     True
X     True
Y     True
Name: e_dept, dtype: bool

In [19]:
#data of employee of IT department
df[df['e_dept'] == 'IT']

   e_id   e_name    e_sal e_dept
C   103    akash  55000.0     IT
X   104  avinash   6700.0     IT
Y   105    atish  42200.1     IT

In [20]:
#we need only salary
df[df['e_dept'] == 'IT']['e_sal']

C    55000.0
X     6700.0
Y    42200.1
Name: e_sal, dtype: float64

In [21]:
#mean of salary
df[df['e_dept'] == 'IT']['e_sal'].mean()

np.float64(34633.36666666667)

#### count of employeee more than 50K salary

In [23]:
df['e_sal'] > 50000

A    False
B    False
C     True
X    False
Y    False
Name: e_sal, dtype: bool

In [24]:
sum(df['e_sal'] > 50000)

1

#### Max Salary from HR Dept

In [25]:
df['e_dept'] == 'HR'

A     True
B     True
C    False
X    False
Y    False
Name: e_dept, dtype: bool

In [26]:
df[df['e_dept'] == 'HR']['e_sal']

A    25000.0
B    17500.5
Name: e_sal, dtype: float64

In [27]:
max(df[df['e_dept'] == 'HR']['e_sal'])

25000.0

#### How many emp from "IT" dept getting less than 60K

In [28]:
df[df['e_dept'] == 'IT']['e_sal']

C    55000.0
X     6700.0
Y    42200.1
Name: e_sal, dtype: float64

In [29]:
df[df['e_dept'] == 'IT']['e_sal'] > 60000

C    False
X    False
Y    False
Name: e_sal, dtype: bool

In [30]:
sum(df[df['e_dept'] == 'IT']['e_sal'] > 60000)

0

#### Name of emp who has highest salary

In [36]:
df['e_sal'].max()

np.float64(55000.0)

In [38]:
max(df['e_sal'])

55000.0

In [39]:
df[df['e_sal'] == df['e_sal'].max()]

   e_id e_name    e_sal e_dept
C   103  akash  55000.0     IT

In [40]:
df[df['e_sal'] == df['e_sal'].max()]['e_name']

C    akash
Name: e_name, dtype: str