# SF Salaries Exercise 

Welcome to a quick exercise for you to practice your pandas skills! We will be using the [SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries) from Kaggle! Just follow along and complete the tasks outlined in bold below. The tasks will get harder and harder as you go along.

** Import pandas as pd.**

In [2]:
import pandas as pd

** Read Salaries.csv as a dataframe called df.**

In [3]:
df = pd.read_csv('Salaries.csv')

C:\Users\Tejas Gaikwad\AppData\Local\Temp\ipykernel_13852\2827120379.py:1: DtypeWarning: Columns (12: Status) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Salaries.csv')

In [3]:
df.shape

(148650, 13)

In [10]:
df.head() # head gives top 5

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [11]:
df.head(2) # we can give how many rows u want from top

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN

In [12]:
df.tail() #normally it is bottom 5

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148645,148646,Carolyn A Wilson,Human Services Technician,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,PT
148646,148648,Joann Anderson,Communications Dispatcher 2,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,PT
148647,148649,Leon Walker,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,PT
148648,148650,Roy I Tillery,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,PT
148649,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,PT

In [13]:
df.tail(2) # we can give how many rows u want from bottom

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148648,148650,Roy I Tillery,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,PT
148649,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,PT

In [14]:
df.columns #gives column names

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='str')

** Check the head of the DataFrame. **

In [16]:
df.tail(3)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148647,148649,Leon Walker,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,PT
148648,148650,Roy I Tillery,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,PT
148649,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,PT

** Use the .info() method to find out how many entries there are.**

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 148650 entries, 0 to 148649
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148650 non-null  int64
 1   EmployeeName      148650 non-null  str
 2   JobTitle          148650 non-null  str
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148650 non-null  float64
 8   TotalPayBenefits  148650 non-null  float64
 9   Year              148650 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148650 non-null  str
 12  Status            38119 non-null   str
dtypes: float64(7), int64(2), str(4)
memory usage: 14.7 MB

In [18]:
df.isna() #It tells the null values if prsent gives true if not it gives false

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,False,False,False,False,False,False,True,False,False,False,True,False,True
1,False,False,False,False,False,False,True,False,False,False,True,False,True
2,False,False,False,False,False,False,True,False,False,False,True,False,True
3,False,False,False,False,False,False,True,False,False,False,True,False,True
4,False,False,False,False,False,False,True,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148645,False,False,False,False,False,False,False,False,False,False,True,False,False
148646,False,False,False,False,False,False,False,False,False,False,True,False,False
148647,False,False,False,False,False,False,False,False,False,False,True,False,False
148648,False,False,False,False,False,False,False,False,False,False,True,False,False
148649,False,False,False,False,False,False,False,False,False,False,True,False,False

In [19]:
df.isna().sum() #it gives the null values count

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                605
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148650
Agency                   0
Status              110531
dtype: int64

**What is the average BasePay ?**

In [20]:
df['BasePay'].mean()

np.float64(66325.44884048769)

In [21]:
print(df['BasePay'].mean())

66325.44884048769

** What is the highest amount of OvertimePay in the dataset ? **

In [22]:
df['OvertimePay'].max()

np.float64(245131.88)

In [23]:
print(df['OvertimePay'].max())

245131.88

** What is the job title of  JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll). **

In [24]:
df[df['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: str

In [26]:
print(df[df['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle'].iloc[0])

CAPTAIN, FIRE SUPPRESSION

** How much does JOSEPH DRISCOLL make (including benefits)? **

In [27]:
df[df['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [29]:
print(df[df['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits'].iloc[0])

270324.91

** What is the name of highest paid person (including benefits)?**

In [30]:
df[df['TotalPayBenefits'].max() == df['TotalPayBenefits']]['EmployeeName']

0    NATHANIEL FORD
Name: EmployeeName, dtype: str

In [31]:
print(df[df['TotalPayBenefits'].max() == df['TotalPayBenefits']]['EmployeeName'].iloc[0])

NATHANIEL FORD

** What is the name of lowest paid person (including benefits)? Do you notice something strange about how much he or she is paid?**

In [34]:
df[df['TotalPayBenefits'].min() == df['TotalPayBenefits']]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148649,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,PT

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148649,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,PT

** What was the average (mean) BasePay of all employees per year? (2011-2014) ? **

In [35]:
df.groupby('Year')['BasePay']

In [36]:
df.groupby('Year')['BasePay'].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

** How many unique job titles are there? **

In [37]:
df['JobTitle'].nunique()

2158

In [38]:
df['JobTitle'].unique()

<StringArray>
[  'GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
                  'CAPTAIN III (POLICE DEPARTMENT)',
             'WIRE ROPE CABLE MAINTENANCE MECHANIC',
     'DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)',
                        'ASSISTANT DEPUTY CHIEF II',
               'BATTALION CHIEF, (FIRE DEPARTMENT)',
                   'DEPUTY DIRECTOR OF INVESTMENTS',
           'CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)',
 'ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)',
                      'EXECUTIVE CONTRACT EMPLOYEE',
 ...
                             'Special Assistant 11',
                      'Hospital Eligibility Worker',
                                'Personnel Trainee',
                      'ACPO,JuvP, Juv Prob (SFERS)',
                        'Apprentice Cement Mason I',
                         'Marina Associate Manager',
                     'Sr Cnselor, Juv Hall (SFERS)',
                   'Forensic Toxicologist Supervis',
                                       'Conversion',
                                        'Cashier 3']
Length: 2158, dtype: str

** What are the top 5 most common jobs? **

In [42]:
df['JobTitle'].value_counts()

JobTitle
Transit Operator                  7036
Special Nurse                     4389
Registered Nurse                  3736
Public Svc Aide-Public Works      2518
Police Officer 3                  2421
                                  ...
Marina Associate Manager             1
Sr Cnselor, Juv Hall (SFERS)         1
Forensic Toxicologist Supervis       1
Conversion                           1
Cashier 3                            1
Name: count, Length: 2158, dtype: int64

In [11]:
df['JobTitle'].value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [12]:
df['JobTitle'].value_counts().head(5).index

Index(['Transit Operator', 'Special Nurse', 'Registered Nurse',
       'Public Svc Aide-Public Works', 'Police Officer 3'],
      dtype='str', name='JobTitle')

In [13]:
df['JobTitle'].value_counts().head(5).index.tolist()

['Transit Operator',
 'Special Nurse',
 'Registered Nurse',
 'Public Svc Aide-Public Works',
 'Police Officer 3']

['Transit Operator',
 'Special Nurse',
 'Registered Nurse',
 'Public Svc Aide-Public Works',
 'Police Officer 3']

** How many Job Titles were represented by only one person in 2013? (e.g. Job Titles with only one occurence in 2013?) **

In [15]:
df[df['Year'] == 2013]['JobTitle']

72925                    Chief of Police
72926             Chief, Fire Department
72927     Battalion Chief, Fire Suppress
72928                  Asst Med Examiner
72929       Dep Dir for Investments, Ret
                       ...
110526           PS Aide Health Services
110527                      Senior Clerk
110528                  Police Officer 3
110529                  Police Officer 3
110530                  Police Officer 3
Name: JobTitle, Length: 37606, dtype: str

In [16]:
df[df['Year'] == 2013]['JobTitle'].value_counts()

JobTitle
Transit Operator                2295
Special Nurse                   1445
Registered Nurse                1231
Public Svc Aide-Public Works     859
Custodian                        789
                                ...
IS Technician Assistant            1
Head Photographer                  1
Animal Control Supervisor          1
Special Assistant 14               1
Senior Assessment Clerk            1
Name: count, Length: 1051, dtype: int64

In [17]:
df[df['Year'] == 2013]['JobTitle'].value_counts() == 1

JobTitle
Transit Operator                False
Special Nurse                   False
Registered Nurse                False
Public Svc Aide-Public Works    False
Custodian                       False
                                ...
IS Technician Assistant          True
Head Photographer                True
Animal Control Supervisor        True
Special Assistant 14             True
Senior Assessment Clerk          True
Name: count, Length: 1051, dtype: bool

In [19]:
sum(df[df['Year'] == 2013]['JobTitle'].value_counts() == 1)

202

In [20]:
#Another Way to do
answer = df[df['Year'] == 2013]['JobTitle'].value_counts().eq(1).sum()

print(answer)

202

** How many people have the word Chief in their job title? (This is pretty tricky) **

In [22]:
df['JobTitle'].str.contains('Chief').sum() #it returns the all cheif contains count

np.int64(423)

In [23]:
df['JobTitle'].str.contains('Chief',case = False).sum() #if the chief CHIEF like the actual content checked by it Uppercese lowercase all things

np.int64(627)

In [24]:
df['JobTitle'].str.contains('Chief',case = False,na = False).sum()

np.int64(627)

In [25]:
df['JobTitle'].str.contains(r'\bChief\b',case = False,na = False).sum()

np.int64(627)

In [26]:
df['JobTitle'].str.split().apply(lambda x: 'Chief' in x).sum()

np.int64(319)

In [28]:
df['JobTitle'].str.contains('chief',case = False,na = False).sum()

np.int64(627)

In [27]:
df['JobTitle'].str.lower().str.split().apply(
    lambda x: 'chief' in x
).sum()

np.int64(477)

In [13]:
sum(df['JobTitle'] == 'Chief')

477

# Great Job!