# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv',sep='\t')

### Step 3. Assign it to a variable called chipo.

In [3]:
df.head(30)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
10,5,1,Chips and Guacamole,NaN,$4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
14,7,1,Chips and Guacamole,NaN,$4.45
15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.49
18,9,2,Canned Soda,[Sprite],$2.18
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75
20,10,1,Chips and Guacamole,NaN,$4.45
21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$8.99
22,11,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",$10.98
24,12,1,Izze,[Grapefruit],$3.39
25,13,1,Chips and Fresh Tomato Salsa,NaN,$2.39
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",$8.49
27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.99
28,14,1,Canned Soda,[Dr. Pepper],$1.09
29,15,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49

### Step 4. How many products cost more than $10.00?

In [4]:
df['item_price_float'] = df['item_price'].apply(lambda price:float(price[1:]))

In [5]:
# df['item_price_float'] = df['item_price_float']/df['quantity']

In [6]:
df[df['item_price_float']>10]['item_name'].nunique()

31

### Step 5. What is the price of each item?
###### print a data frame with only two columns item_name and item_price

In [7]:
df[["item_name","item_price"]]

                                  item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39
1                                      Izze     $3.39
2                          Nantucket Nectar     $3.39
3     Chips and Tomatillo-Green Chili Salsa     $2.39
4                              Chicken Bowl    $16.98
...                                     ...        ...
4617                          Steak Burrito    $11.75
4618                          Steak Burrito    $11.75
4619                     Chicken Salad Bowl    $11.25
4620                     Chicken Salad Bowl     $8.75
4621                     Chicken Salad Bowl     $8.75

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [8]:
df.sort_values(by = "item_name")

,order_id,quantity,item_name,choice_description,item_price,item_price_float
298,129,1,6 Pack Soft Drink,[Sprite],$6.49,6.49
341,148,1,6 Pack Soft Drink,[Diet Coke],$6.49,6.49
357,154,1,6 Pack Soft Drink,[Coke],$6.49,6.49
388,168,1,6 Pack Soft Drink,[Diet Coke],$6.49,6.49
417,182,1,6 Pack Soft Drink,[Diet Coke],$6.49,6.49
...,...,...,...,...,...,...
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",$8.49,8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25,11.25
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",$8.49,8.49
3889,1559,2,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$16.98,16.98

### Step 7. What was the quantity of the most expensive item ordered?

In [9]:
sum(df[df["item_price_float"].max() == df["item_price_float"]]["quantity"])

15

In [10]:
price = df["item_price"].str.replace("$", "", regex=False).astype(float)

df.loc[price == price.max(), "quantity"].sum()

np.int64(15)

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [11]:
sum(df["item_name"] == "Veggie Salad Bowl")

18

### Step 9. How many times did someone order more than one Canned Soda?

In [12]:
sum((df["item_name"] == "Canned Soda") & (df["quantity"] > 1))

20

### Step 10. What is the order id of order with the highest total price of all items ordered in that order?

In [13]:
# df[df["item_price_float"].max() == df["item_price_float"]]["order_id"]

In [14]:
df.groupby("order_id")["item_price_float"].sum().idxmax()

np.int64(926)

### Step 11. In How many orders, atleast one items is ordered multiple times?

In [15]:
df[df["quantity"] > 1]["order_id"].nunique()

233

In [17]:
# df.head(20)

### Step 12. Create a billing report (dataframe) which has columns as 'Order_Id', 'Total_Bill', 'Total Bill After Discount'. Restaurant owner has decided to give discount of 5% on orders of above $50 total cost.

In [18]:
df_billingreport = pd.DataFrame(
    {
        "Total_Bill" : df["order_id"],
        "Total_Bill" : df["item_price_float"]
        
    }
)

In [19]:
df_billingreport

      Total_Bill
0           2.39
1           3.39
2           3.39
3           2.39
4          16.98
...          ...
4617       11.75
4618       11.75
4619       11.25
4620        8.75
4621        8.75

[4622 rows x 1 columns]

In [20]:
df_billingreport["Total Bill After Discount"] = df_billingreport["Total_Bill"].apply(lambda x : (x * 0.95) if x > 50 else x)

In [21]:
df_billingreport

      Total_Bill  Total Bill After Discount
0           2.39                       2.39
1           3.39                       3.39
2           3.39                       3.39
3           2.39                       2.39
4          16.98                      16.98
...          ...                        ...
4617       11.75                      11.75
4618       11.75                      11.75
4619       11.25                      11.25
4620        8.75                       8.75
4621        8.75                       8.75

[4622 rows x 2 columns]

In [22]:
sum(df_billingreport["Total_Bill"] > 50)

0