In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../../datasets/Obesity Classification.csv")
df.head()

   ID  Age  Gender  Height  Weight   BMI          Label
0   1   25    Male     175      80  25.3  Normal Weight
1   2   30  Female     160      60  22.5  Normal Weight
2   3   35    Male     180      90  27.3     Overweight
3   4   40  Female     150      50  20.0    Underweight
4   5   45    Male     190     100  31.2          Obese

In [3]:
df.shape

(108, 7)

In [4]:
df["Gender"] = df["Gender"].apply(lambda x : 1 if x == "Male" else 0)
df.head()

   ID  Age  Gender  Height  Weight   BMI          Label
0   1   25       1     175      80  25.3  Normal Weight
1   2   30       0     160      60  22.5  Normal Weight
2   3   35       1     180      90  27.3     Overweight
3   4   40       0     150      50  20.0    Underweight
4   5   45       1     190     100  31.2          Obese

In [12]:
df["Label"] = df["Label"].apply(lambda x : 1 if x == "Normal Weight" else 2 if x == "Overweight" else 3 if x == "Underweight" else 4)

In [19]:
X = df[["Age","BMI"]]
y = df["Label"]

In [20]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X,y)
model.score(X,y)

C:\Users\Tejas Gaikwad\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.9537037037037037

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=49)

In [22]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_scaler = scaler.transform(X_train)

In [23]:
X_test_scaler = scaler.transform(X_test)

In [24]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
models = {
    "Linear" : LinearRegression(),
    "Logis" : LogisticRegression(),
    "KNN1" : KNeighborsClassifier(n_neighbors=1),
    "KNN3" : KNeighborsClassifier(n_neighbors=3),
    "KNN5" : KNeighborsClassifier(n_neighbors=5),
    "KNN7" : KNeighborsClassifier(n_neighbors=7),
    "KNN9" : KNeighborsClassifier(n_neighbors=9)
}
for name,model in models.items():
    model.fit(X_train_scaler,y_train)
    sc = model.score(X_test_scaler,y_test)
    print(sc)

0.06806864886369934
0.5757575757575758
0.8787878787878788
0.7878787878787878
0.7575757575757576
0.8181818181818182
0.8181818181818182