In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../../datasets/Car Dataset Processed - Car Dataset Processed.csv")
df.head()

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.81,2996,2996,333,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.40,999,999,9863,8.99
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20.68,1995,1995,188,23.75
3,3,2019 Kia Seltos GTX Plus,Dec-19,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16.50,1353,1353,13808,13.56
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14.67,1798,1798,17746,24.00

In [3]:
df.describe()

,Unnamed: 0,seats,kms_driven,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
count,1499.000000,1499.000000,1499.00000,1499.000000,1499.000000,1.499000e+03,1.499000e+03,1.499000e+03,1499.000000
mean,783.119413,5.206137,53219.61441,2017.380921,187.284703,1.521934e+10,1.521934e+10,1.274292e+04,171.506071
std,448.046260,0.636718,40404.02744,2.996381,516.597348,2.222352e+11,2.222352e+11,8.269170e+04,3540.885094
min,0.000000,4.000000,620.00000,2007.000000,7.810000,6.700000e+01,6.700000e+01,1.900000e+01,1.000000
25%,401.500000,5.000000,30000.00000,2015.000000,16.100000,1.197000e+03,1.197000e+03,5.000000e+02,4.635000
50%,791.000000,5.000000,49441.00000,2018.000000,18.760000,1.493000e+03,1.493000e+03,1.176000e+03,6.950000
75%,1168.500000,5.000000,70000.00000,2019.000000,21.400000,1.995000e+03,1.995000e+03,8.850000e+03,16.000000
max,1552.000000,8.000000,810000.00000,2023.000000,3996.000000,3.258640e+12,3.258640e+12,1.186600e+06,95000.000000

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1499 entries, 0 to 1498
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          1499 non-null   int64
 1   car_name            1499 non-null   str
 2   registration_year   1499 non-null   str
 3   insurance_validity  1499 non-null   str
 4   fuel_type           1499 non-null   str
 5   seats               1499 non-null   int64
 6   kms_driven          1499 non-null   int64
 7   ownsership          1499 non-null   str
 8   transmission        1499 non-null   str
 9   manufacturing_year  1499 non-null   int64
 10  mileage(kmpl)       1499 non-null   float64
 11  engine(cc)          1499 non-null   int64
 12  max_power(bhp)      1499 non-null   int64
 13  torque(Nm)          1499 non-null   int64
 14  price(in lakhs)     1499 non-null   float64
dtypes: float64(2), int64(7), str(6)
memory usage: 286.6 KB

In [5]:
df.shape

(1499, 15)

In [6]:
df["car_company"] = df["car_name"].apply(lambda x : x.split()[1])

In [7]:
df.head()

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs),car_company
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.81,2996,2996,333,63.75,Mercedes-Benz
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.40,999,999,9863,8.99,Nissan
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20.68,1995,1995,188,23.75,BMW
3,3,2019 Kia Seltos GTX Plus,Dec-19,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16.50,1353,1353,13808,13.56,Kia
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14.67,1798,1798,17746,24.00,Skoda

In [8]:
df["car_name"].str.split()

0                    [2017, Mercedes-Benz, S-Class, S400]
1       [2020, Nissan, Magnite, Turbo, CVT, XV, Premiu...
2                     [2018, BMW, X1, sDrive, 20d, xLine]
3                          [2019, Kia, Seltos, GTX, Plus]
4                 [2019, Skoda, Superb, LK, 1.8, TSI, AT]
                              ...
1494                     [2022, Maruti, Ertiga, VXI, CNG]
1495    [2020, Hyundai, Creta, SX, Opt, Diesel, AT, BSVI]
1496                       [2017, Honda, WR-V, i-VTEC, S]
1497      [2018, Volkswagen, Polo, 1.0, MPI, Comfortline]
1498                    [2018, Maruti, Swift, Dzire, VXI]
Name: car_name, Length: 1499, dtype: object

In [9]:
df["car_name"]

0                         2017 Mercedes-Benz S-Class S400
1       2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI
2                            2018 BMW X1 sDrive 20d xLine
3                                2019 Kia Seltos GTX Plus
4                         2019 Skoda Superb LK 1.8 TSI AT
                              ...
1494                           2022 Maruti Ertiga VXI CNG
1495             2020 Hyundai Creta SX Opt Diesel AT BSVI
1496                             2017 Honda WR-V i-VTEC S
1497             2018 Volkswagen Polo 1.0 MPI Comfortline
1498                          2018 Maruti Swift Dzire VXI
Name: car_name, Length: 1499, dtype: str

In [10]:
df["car_model"] = df["car_name"].apply(lambda x : x.split()[2:])
df["car_model"] = df["car_model"].apply(lambda x : " ".join(x))
df.head()

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs),car_company,car_model
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.81,2996,2996,333,63.75,Mercedes-Benz,S-Class S400
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.40,999,999,9863,8.99,Nissan,Magnite Turbo CVT XV Premium Opt BSVI
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20.68,1995,1995,188,23.75,BMW,X1 sDrive 20d xLine
3,3,2019 Kia Seltos GTX Plus,Dec-19,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16.50,1353,1353,13808,13.56,Kia,Seltos GTX Plus
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14.67,1798,1798,17746,24.00,Skoda,Superb LK 1.8 TSI AT

In [11]:
df['insurance_validity'].value_counts()

insurance_validity
Comprehensive            1081
Third Party insurance     289
Zero Dep                   64
Third Party                63
Not Available               2
Name: count, dtype: int64

In [12]:
df['insurance_validity'].info()

<class 'pandas.Series'>
RangeIndex: 1499 entries, 0 to 1498
Series name: insurance_validity
Non-Null Count  Dtype
--------------  -----
1499 non-null   str
dtypes: str(1)
memory usage: 32.7 KB

In [13]:
df['insurance_validity'] = df['insurance_validity'].apply(lambda x : 1 if x.strip().title() == "Comprehensive" else 2 if x.strip().title() == "Zero dep" else 3 )

1 = Comprehensive
2 = Zero dep
3 = others

In [14]:
df

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs),car_company,car_model
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,1,Petrol,5,56000,First Owner,Automatic,2017,7.81,2996,2996,333,63.75,Mercedes-Benz,S-Class S400
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,1,Petrol,5,30615,First Owner,Automatic,2020,17.40,999,999,9863,8.99,Nissan,Magnite Turbo CVT XV Premium Opt BSVI
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,1,Diesel,5,24000,First Owner,Automatic,2018,20.68,1995,1995,188,23.75,BMW,X1 sDrive 20d xLine
3,3,2019 Kia Seltos GTX Plus,Dec-19,1,Petrol,5,18378,First Owner,Manual,2019,16.50,1353,1353,13808,13.56,Kia,Seltos GTX Plus
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,1,Petrol,5,44900,First Owner,Automatic,2019,14.67,1798,1798,17746,24.00,Skoda,Superb LK 1.8 TSI AT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1547,2022 Maruti Ertiga VXI CNG,May-22,3,CNG,7,26500,First Owner,Manual,2022,26.11,1462,1462,8663,11.50,Maruti,Ertiga VXI CNG
1495,1548,2020 Hyundai Creta SX Opt Diesel AT BSVI,Aug-20,1,Diesel,5,35000,First Owner,Automatic,2020,1493.00,11345,11345,250,17.41,Hyundai,Creta SX Opt Diesel AT BSVI
1496,1550,2017 Honda WR-V i-VTEC S,Jun-17,1,Petrol,5,49000,First Owner,Manual,2017,17.50,1199,1199,887,5.85,Honda,WR-V i-VTEC S
1497,1551,2018 Volkswagen Polo 1.0 MPI Comfortline,May-18,1,Petrol,5,40000,Second Owner,Manual,2018,18.78,999,999,75,4.75,Volkswagen,Polo 1.0 MPI Comfortline
1498,1552,2018 Maruti Swift Dzire VXI,May-18,1,Petrol,5,34756,First Owner,Manual,2018,20.85,1197,1197,8314,6.10,Maruti,Swift Dzire VXI

In [15]:
df["fuel_type"].value_counts()

fuel_type
Petrol    997
Diesel    480
CNG        22
Name: count, dtype: int64

1 = Petrol
2 = Diesel    
3 = CNG

In [16]:
df['fuel_type'] = df['fuel_type'].apply(lambda x : 1 if x.strip().title() == "Petrol" else 2 if x.strip().title() == "Diesel" else 3 )
df

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs),car_company,car_model
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,1,1,5,56000,First Owner,Automatic,2017,7.81,2996,2996,333,63.75,Mercedes-Benz,S-Class S400
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,1,1,5,30615,First Owner,Automatic,2020,17.40,999,999,9863,8.99,Nissan,Magnite Turbo CVT XV Premium Opt BSVI
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,1,2,5,24000,First Owner,Automatic,2018,20.68,1995,1995,188,23.75,BMW,X1 sDrive 20d xLine
3,3,2019 Kia Seltos GTX Plus,Dec-19,1,1,5,18378,First Owner,Manual,2019,16.50,1353,1353,13808,13.56,Kia,Seltos GTX Plus
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,1,1,5,44900,First Owner,Automatic,2019,14.67,1798,1798,17746,24.00,Skoda,Superb LK 1.8 TSI AT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1547,2022 Maruti Ertiga VXI CNG,May-22,3,3,7,26500,First Owner,Manual,2022,26.11,1462,1462,8663,11.50,Maruti,Ertiga VXI CNG
1495,1548,2020 Hyundai Creta SX Opt Diesel AT BSVI,Aug-20,1,2,5,35000,First Owner,Automatic,2020,1493.00,11345,11345,250,17.41,Hyundai,Creta SX Opt Diesel AT BSVI
1496,1550,2017 Honda WR-V i-VTEC S,Jun-17,1,1,5,49000,First Owner,Manual,2017,17.50,1199,1199,887,5.85,Honda,WR-V i-VTEC S
1497,1551,2018 Volkswagen Polo 1.0 MPI Comfortline,May-18,1,1,5,40000,Second Owner,Manual,2018,18.78,999,999,75,4.75,Volkswagen,Polo 1.0 MPI Comfortline
1498,1552,2018 Maruti Swift Dzire VXI,May-18,1,1,5,34756,First Owner,Manual,2018,20.85,1197,1197,8314,6.10,Maruti,Swift Dzire VXI

In [17]:
df["ownsership"].value_counts()

ownsership
First Owner     1236
Second Owner     240
Third Owner       21
Fifth Owner        2
Name: count, dtype: int64

In [18]:
df["ownsership"] = df["ownsership"].apply(lambda x : 1 if x.strip().title() == "First Owner" else 2 if x.strip().title() == "Second Owner" else 3 if x.strip().title() == "Third Owner" else 5)
df

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs),car_company,car_model
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,1,1,5,56000,1,Automatic,2017,7.81,2996,2996,333,63.75,Mercedes-Benz,S-Class S400
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,1,1,5,30615,1,Automatic,2020,17.40,999,999,9863,8.99,Nissan,Magnite Turbo CVT XV Premium Opt BSVI
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,1,2,5,24000,1,Automatic,2018,20.68,1995,1995,188,23.75,BMW,X1 sDrive 20d xLine
3,3,2019 Kia Seltos GTX Plus,Dec-19,1,1,5,18378,1,Manual,2019,16.50,1353,1353,13808,13.56,Kia,Seltos GTX Plus
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,1,1,5,44900,1,Automatic,2019,14.67,1798,1798,17746,24.00,Skoda,Superb LK 1.8 TSI AT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1547,2022 Maruti Ertiga VXI CNG,May-22,3,3,7,26500,1,Manual,2022,26.11,1462,1462,8663,11.50,Maruti,Ertiga VXI CNG
1495,1548,2020 Hyundai Creta SX Opt Diesel AT BSVI,Aug-20,1,2,5,35000,1,Automatic,2020,1493.00,11345,11345,250,17.41,Hyundai,Creta SX Opt Diesel AT BSVI
1496,1550,2017 Honda WR-V i-VTEC S,Jun-17,1,1,5,49000,1,Manual,2017,17.50,1199,1199,887,5.85,Honda,WR-V i-VTEC S
1497,1551,2018 Volkswagen Polo 1.0 MPI Comfortline,May-18,1,1,5,40000,2,Manual,2018,18.78,999,999,75,4.75,Volkswagen,Polo 1.0 MPI Comfortline
1498,1552,2018 Maruti Swift Dzire VXI,May-18,1,1,5,34756,1,Manual,2018,20.85,1197,1197,8314,6.10,Maruti,Swift Dzire VXI

In [19]:
df["transmission"].value_counts()

transmission
Manual       832
Automatic    667
Name: count, dtype: int64

In [20]:
df["transmission"] = df["transmission"].apply(lambda x : 0 if x == "Manual" else 1)
df

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs),car_company,car_model
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,1,1,5,56000,1,1,2017,7.81,2996,2996,333,63.75,Mercedes-Benz,S-Class S400
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,1,1,5,30615,1,1,2020,17.40,999,999,9863,8.99,Nissan,Magnite Turbo CVT XV Premium Opt BSVI
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,1,2,5,24000,1,1,2018,20.68,1995,1995,188,23.75,BMW,X1 sDrive 20d xLine
3,3,2019 Kia Seltos GTX Plus,Dec-19,1,1,5,18378,1,0,2019,16.50,1353,1353,13808,13.56,Kia,Seltos GTX Plus
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,1,1,5,44900,1,1,2019,14.67,1798,1798,17746,24.00,Skoda,Superb LK 1.8 TSI AT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1547,2022 Maruti Ertiga VXI CNG,May-22,3,3,7,26500,1,0,2022,26.11,1462,1462,8663,11.50,Maruti,Ertiga VXI CNG
1495,1548,2020 Hyundai Creta SX Opt Diesel AT BSVI,Aug-20,1,2,5,35000,1,1,2020,1493.00,11345,11345,250,17.41,Hyundai,Creta SX Opt Diesel AT BSVI
1496,1550,2017 Honda WR-V i-VTEC S,Jun-17,1,1,5,49000,1,0,2017,17.50,1199,1199,887,5.85,Honda,WR-V i-VTEC S
1497,1551,2018 Volkswagen Polo 1.0 MPI Comfortline,May-18,1,1,5,40000,2,0,2018,18.78,999,999,75,4.75,Volkswagen,Polo 1.0 MPI Comfortline
1498,1552,2018 Maruti Swift Dzire VXI,May-18,1,1,5,34756,1,0,2018,20.85,1197,1197,8314,6.10,Maruti,Swift Dzire VXI

In [21]:
df["how_old"] = 2026 - df["manufacturing_year"] 
df

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs),car_company,car_model,how_old
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,1,1,5,56000,1,1,2017,7.81,2996,2996,333,63.75,Mercedes-Benz,S-Class S400,9
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,1,1,5,30615,1,1,2020,17.40,999,999,9863,8.99,Nissan,Magnite Turbo CVT XV Premium Opt BSVI,6
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,1,2,5,24000,1,1,2018,20.68,1995,1995,188,23.75,BMW,X1 sDrive 20d xLine,8
3,3,2019 Kia Seltos GTX Plus,Dec-19,1,1,5,18378,1,0,2019,16.50,1353,1353,13808,13.56,Kia,Seltos GTX Plus,7
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,1,1,5,44900,1,1,2019,14.67,1798,1798,17746,24.00,Skoda,Superb LK 1.8 TSI AT,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1547,2022 Maruti Ertiga VXI CNG,May-22,3,3,7,26500,1,0,2022,26.11,1462,1462,8663,11.50,Maruti,Ertiga VXI CNG,4
1495,1548,2020 Hyundai Creta SX Opt Diesel AT BSVI,Aug-20,1,2,5,35000,1,1,2020,1493.00,11345,11345,250,17.41,Hyundai,Creta SX Opt Diesel AT BSVI,6
1496,1550,2017 Honda WR-V i-VTEC S,Jun-17,1,1,5,49000,1,0,2017,17.50,1199,1199,887,5.85,Honda,WR-V i-VTEC S,9
1497,1551,2018 Volkswagen Polo 1.0 MPI Comfortline,May-18,1,1,5,40000,2,0,2018,18.78,999,999,75,4.75,Volkswagen,Polo 1.0 MPI Comfortline,8
1498,1552,2018 Maruti Swift Dzire VXI,May-18,1,1,5,34756,1,0,2018,20.85,1197,1197,8314,6.10,Maruti,Swift Dzire VXI,8

In [22]:
x = df.drop("price(in lakhs)", axis=1)
y = df["price(in lakhs)"]

In [23]:
print(x.dtypes)
print(y.dtype)

Unnamed: 0              int64
car_name                  str
registration_year         str
insurance_validity      int64
fuel_type               int64
seats                   int64
kms_driven              int64
ownsership              int64
transmission            int64
manufacturing_year      int64
mileage(kmpl)         float64
engine(cc)              int64
max_power(bhp)          int64
torque(Nm)              int64
car_company               str
car_model                 str
how_old                 int64
dtype: object
float64

In [24]:
x = pd.get_dummies(x, dtype=int)

In [25]:
data = pd.concat([x, y], axis=1).dropna()

x = data.drop("price(in lakhs)", axis=1)
y = data["price(in lakhs)"]

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [27]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [28]:
from sklearn.metrics import r2_score, mean_absolute_error

y_pred = model.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))

R2 Score: -122.12710300120713
MAE: 196.64413344496108

In [29]:
print("Predicted Price:", model.predict(X_test.iloc[[0]])[0])
print("Actual Price:", y_test.iloc[0])

Predicted Price: 211.84523350231183
Actual Price: 8.75

In [30]:
model.score(x,y) * 100

-0.011332621352488914

In [31]:
df["car_company"].unique()

<ArrowStringArray>
['Mercedes-Benz',        'Nissan',           'BMW',           'Kia',
         'Skoda',         'Honda',       'Hyundai',          'Tata',
       'Renault',          'Ford',          'Jeep',            'MG',
        'Maruti',          'Audi',        'Toyota',        'Jaguar',
    'Volkswagen',      'Mahindra',         'Volvo',          'Land',
         'Isuzu',    'Mitsubishi',       'Porsche',        'Datsun',
         'Lexus',          'Mini',          'Fiat',   'Lamborghini']
Length: 28, dtype: str

In [32]:
df["car_company"].nunique()

28

brand_classes = {
    'Mercedes-Benz': 'Luxury',
    'BMW': 'Luxury',
    'Audi': 'Luxury',
    'Jaguar': 'Luxury',
    'Volvo': 'Luxury',
    'Porsche': 'Luxury',
    'Lexus': 'Luxury',
    'Mini': 'Luxury',
    'Lamborghini': 'Luxury',

    'Nissan': 'Mid-range',
    'Kia': 'Mid-range',
    'Skoda': 'Mid-range',
    'Honda': 'Mid-range',
    'Hyundai': 'Mid-range',
    'Renault': 'Mid-range',
    'Ford': 'Mid-range',
    'Jeep': 'Mid-range',
    'MG': 'Mid-range',
    'Toyota': 'Mid-range',
    'Volkswagen': 'Mid-range',
    'Mahindra': 'Mid-range',
    'Isuzu': 'Mid-range',
    'Mitsubishi': 'Mid-range',
    'Fiat': 'Mid-range',

    'Tata': 'Economy',
    'Maruti': 'Economy',
    'Datsun': 'Economy'
}

In [33]:
brand_classes_numeric = {
    'Mercedes-Benz': 1,  # Luxury
    'BMW': 1,            # Luxury
    'Audi': 1,           # Luxury
    'Jaguar': 1,         # Luxury
    'Volvo': 1,          # Luxury
    'Porsche': 1,        # Luxury
    'Lexus': 1,          # Luxury
    'Mini': 1,           # Luxury
    'Lamborghini': 1,    # Luxury
    'Land': 1,           # Luxury (assuming Land Rover)

    'Nissan': 2,         # Mid-range
    'Kia': 2,            # Mid-range
    'Skoda': 2,          # Mid-range
    'Honda': 2,          # Mid-range
    'Hyundai': 2,        # Mid-range
    'Renault': 2,        # Mid-range
    'Ford': 2,           # Mid-range
    'Jeep': 2,           # Mid-range
    'MG': 2,             # Mid-range
    'Toyota': 2,         # Mid-range
    'Volkswagen': 2,     # Mid-range
    'Mahindra': 2,       # Mid-range
    'Isuzu': 2,          # Mid-range
    'Mitsubishi': 2,     # Mid-range
    'Fiat': 2,           # Mid-range

    'Tata': 3,           # Economy
    'Maruti': 3,         # Economy
    'Datsun': 3          # Economy
}

In [34]:
df["class"] = df["car_company"].map(brand_classes_numeric)

In [35]:
df

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs),car_company,car_model,how_old,class
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,1,1,5,56000,1,1,2017,7.81,2996,2996,333,63.75,Mercedes-Benz,S-Class S400,9,1
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,1,1,5,30615,1,1,2020,17.40,999,999,9863,8.99,Nissan,Magnite Turbo CVT XV Premium Opt BSVI,6,2
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,1,2,5,24000,1,1,2018,20.68,1995,1995,188,23.75,BMW,X1 sDrive 20d xLine,8,1
3,3,2019 Kia Seltos GTX Plus,Dec-19,1,1,5,18378,1,0,2019,16.50,1353,1353,13808,13.56,Kia,Seltos GTX Plus,7,2
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,1,1,5,44900,1,1,2019,14.67,1798,1798,17746,24.00,Skoda,Superb LK 1.8 TSI AT,7,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1547,2022 Maruti Ertiga VXI CNG,May-22,3,3,7,26500,1,0,2022,26.11,1462,1462,8663,11.50,Maruti,Ertiga VXI CNG,4,3
1495,1548,2020 Hyundai Creta SX Opt Diesel AT BSVI,Aug-20,1,2,5,35000,1,1,2020,1493.00,11345,11345,250,17.41,Hyundai,Creta SX Opt Diesel AT BSVI,6,2
1496,1550,2017 Honda WR-V i-VTEC S,Jun-17,1,1,5,49000,1,0,2017,17.50,1199,1199,887,5.85,Honda,WR-V i-VTEC S,9,2
1497,1551,2018 Volkswagen Polo 1.0 MPI Comfortline,May-18,1,1,5,40000,2,0,2018,18.78,999,999,75,4.75,Volkswagen,Polo 1.0 MPI Comfortline,8,2
1498,1552,2018 Maruti Swift Dzire VXI,May-18,1,1,5,34756,1,0,2018,20.85,1197,1197,8314,6.10,Maruti,Swift Dzire VXI,8,3

In [36]:
df["class"].isna().sum()

np.int64(0)

In [37]:
df["car_name"].isna().sum()

np.int64(0)

In [38]:
# class_codes = {'Luxury': 1, 'Mid-range': 2, 'Economy': 3}
# df['class'] = df['class'].map(class_codes)
# df

# making the km proper

In [39]:
df['kms_class'] = pd.qcut(df['kms_driven'], q=4, labels=[1, 2, 3, 4])
df

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs),car_company,car_model,how_old,class,kms_class
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,1,1,5,56000,1,1,2017,7.81,2996,2996,333,63.75,Mercedes-Benz,S-Class S400,9,1,3
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,1,1,5,30615,1,1,2020,17.40,999,999,9863,8.99,Nissan,Magnite Turbo CVT XV Premium Opt BSVI,6,2,2
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,1,2,5,24000,1,1,2018,20.68,1995,1995,188,23.75,BMW,X1 sDrive 20d xLine,8,1,1
3,3,2019 Kia Seltos GTX Plus,Dec-19,1,1,5,18378,1,0,2019,16.50,1353,1353,13808,13.56,Kia,Seltos GTX Plus,7,2,1
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,1,1,5,44900,1,1,2019,14.67,1798,1798,17746,24.00,Skoda,Superb LK 1.8 TSI AT,7,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1547,2022 Maruti Ertiga VXI CNG,May-22,3,3,7,26500,1,0,2022,26.11,1462,1462,8663,11.50,Maruti,Ertiga VXI CNG,4,3,1
1495,1548,2020 Hyundai Creta SX Opt Diesel AT BSVI,Aug-20,1,2,5,35000,1,1,2020,1493.00,11345,11345,250,17.41,Hyundai,Creta SX Opt Diesel AT BSVI,6,2,2
1496,1550,2017 Honda WR-V i-VTEC S,Jun-17,1,1,5,49000,1,0,2017,17.50,1199,1199,887,5.85,Honda,WR-V i-VTEC S,9,2,2
1497,1551,2018 Volkswagen Polo 1.0 MPI Comfortline,May-18,1,1,5,40000,2,0,2018,18.78,999,999,75,4.75,Volkswagen,Polo 1.0 MPI Comfortline,8,2,2
1498,1552,2018 Maruti Swift Dzire VXI,May-18,1,1,5,34756,1,0,2018,20.85,1197,1197,8314,6.10,Maruti,Swift Dzire VXI,8,3,2

In [40]:
df['kms_class'] = df['kms_class'].astype(int)

In [41]:
df["engine(cc)"].describe()

count    1.499000e+03
mean     1.521934e+10
std      2.222352e+11
min      6.700000e+01
25%      1.197000e+03
50%      1.493000e+03
75%      1.995000e+03
max      3.258640e+12
Name: engine(cc), dtype: float64

In [42]:
sum(df["engine(cc)"] > 4000)

102

In [43]:
sum(df["engine(cc)"] < 800)

75

In [44]:
df[(df["engine(cc)"] > 4000) | (df["engine(cc)"] < 800)].fillna(0)

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs),car_company,car_model,how_old,class,kms_class
23,23,2011 Maruti Wagon R LXI BSIII,Aug-11,1,1,5,40191,2,0,2011,998.0,671,671,90,2.12,Maruti,Wagon R LXI BSIII,15,3,2
43,43,2011 Maruti Wagon R LXI BSIII,Aug-11,1,1,5,40191,2,0,2011,998.0,671,671,90,2.12,Maruti,Wagon R LXI BSIII,15,3,2
75,75,2018 Maruti Wagon R CNG LXI,Feb-18,1,3,5,45000,1,0,2018,998.0,5833,5833,78,4.45,Maruti,Wagon R CNG LXI,8,3,2
79,79,2018 Mahindra XUV500 W5,Jul-18,3,2,7,62000,2,0,2018,2179.0,15287,15287,360,8.50,Mahindra,XUV500 W5,8,2,3
95,95,2018 Maruti Wagon R CNG LXI,Feb-18,1,3,5,45000,1,0,2018,998.0,5833,5833,78,4.45,Maruti,Wagon R CNG LXI,8,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1472,1525,2021 MG Hector Sharp CVT,2021,3,1,5,40000,2,1,2021,1451.0,141,141,250,16.00,MG,Hector Sharp CVT,5,2,2
1473,1526,2010 Hyundai i10 Magna 1.2,Jan-10,3,1,5,45221,1,0,2010,1197.0,789,789,1117,2.35,Hyundai,i10 Magna 1.2,16,2,2
1483,1536,2020 MG Hector Hybrid Sharp MT,Feb-20,1,1,5,15071,1,0,2020,1451.0,141,141,250,14.28,MG,Hector Hybrid Sharp MT,6,2,1
1492,1545,2022 Maruti Ignis Sigma BSVI,2022,3,1,5,2300,1,0,2022,1197.0,8180,8180,113,5.90,Maruti,Ignis Sigma BSVI,4,3,1
1495,1548,2020 Hyundai Creta SX Opt Diesel AT BSVI,Aug-20,1,2,5,35000,1,1,2020,1493.0,11345,11345,250,17.41,Hyundai,Creta SX Opt Diesel AT BSVI,6,2,2

In [45]:
df["engine_enc"] = df["engine(cc)"].apply(lambda x : 1 if x < 800 else 2 if  x < 1500 else 3 if x < 2500 else 4 if x < 3500 else 0)
df

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,...,engine(cc),max_power(bhp),torque(Nm),price(in lakhs),car_company,car_model,how_old,class,kms_class,engine_enc
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,1,1,5,56000,1,1,2017,...,2996,2996,333,63.75,Mercedes-Benz,S-Class S400,9,1,3,4
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,1,1,5,30615,1,1,2020,...,999,999,9863,8.99,Nissan,Magnite Turbo CVT XV Premium Opt BSVI,6,2,2,2
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,1,2,5,24000,1,1,2018,...,1995,1995,188,23.75,BMW,X1 sDrive 20d xLine,8,1,1,3
3,3,2019 Kia Seltos GTX Plus,Dec-19,1,1,5,18378,1,0,2019,...,1353,1353,13808,13.56,Kia,Seltos GTX Plus,7,2,1,2
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,1,1,5,44900,1,1,2019,...,1798,1798,17746,24.00,Skoda,Superb LK 1.8 TSI AT,7,2,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1547,2022 Maruti Ertiga VXI CNG,May-22,3,3,7,26500,1,0,2022,...,1462,1462,8663,11.50,Maruti,Ertiga VXI CNG,4,3,1,2
1495,1548,2020 Hyundai Creta SX Opt Diesel AT BSVI,Aug-20,1,2,5,35000,1,1,2020,...,11345,11345,250,17.41,Hyundai,Creta SX Opt Diesel AT BSVI,6,2,2,0
1496,1550,2017 Honda WR-V i-VTEC S,Jun-17,1,1,5,49000,1,0,2017,...,1199,1199,887,5.85,Honda,WR-V i-VTEC S,9,2,2,2
1497,1551,2018 Volkswagen Polo 1.0 MPI Comfortline,May-18,1,1,5,40000,2,0,2018,...,999,999,75,4.75,Volkswagen,Polo 1.0 MPI Comfortline,8,2,2,2
1498,1552,2018 Maruti Swift Dzire VXI,May-18,1,1,5,34756,1,0,2018,...,1197,1197,8314,6.10,Maruti,Swift Dzire VXI,8,3,2,2

In [46]:
df.head(1)

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,...,engine(cc),max_power(bhp),torque(Nm),price(in lakhs),car_company,car_model,how_old,class,kms_class,engine_enc
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,1,1,5,56000,1,1,2017,...,2996,2996,333,63.75,Mercedes-Benz,S-Class S400,9,1,3,4

In [47]:
df.head(1)

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,...,engine(cc),max_power(bhp),torque(Nm),price(in lakhs),car_company,car_model,how_old,class,kms_class,engine_enc
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,1,1,5,56000,1,1,2017,...,2996,2996,333,63.75,Mercedes-Benz,S-Class S400,9,1,3,4

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1499 entries, 0 to 1498
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          1499 non-null   int64
 1   car_name            1499 non-null   str
 2   registration_year   1499 non-null   str
 3   insurance_validity  1499 non-null   int64
 4   fuel_type           1499 non-null   int64
 5   seats               1499 non-null   int64
 6   kms_driven          1499 non-null   int64
 7   ownsership          1499 non-null   int64
 8   transmission        1499 non-null   int64
 9   manufacturing_year  1499 non-null   int64
 10  mileage(kmpl)       1499 non-null   float64
 11  engine(cc)          1499 non-null   int64
 12  max_power(bhp)      1499 non-null   int64
 13  torque(Nm)          1499 non-null   int64
 14  price(in lakhs)     1499 non-null   float64
 15  car_company         1499 non-null   str
 16  car_model           1499 non-null   str
 17  how_old             1499 non-null   int64
 18  class               1499 non-null   int64
 19  kms_class           1499 non-null   int64
 20  engine_enc          1499 non-null   int64
dtypes: float64(2), int64(15), str(4)
memory usage: 336.9 KB

In [49]:
df

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,...,engine(cc),max_power(bhp),torque(Nm),price(in lakhs),car_company,car_model,how_old,class,kms_class,engine_enc
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,1,1,5,56000,1,1,2017,...,2996,2996,333,63.75,Mercedes-Benz,S-Class S400,9,1,3,4
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,1,1,5,30615,1,1,2020,...,999,999,9863,8.99,Nissan,Magnite Turbo CVT XV Premium Opt BSVI,6,2,2,2
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,1,2,5,24000,1,1,2018,...,1995,1995,188,23.75,BMW,X1 sDrive 20d xLine,8,1,1,3
3,3,2019 Kia Seltos GTX Plus,Dec-19,1,1,5,18378,1,0,2019,...,1353,1353,13808,13.56,Kia,Seltos GTX Plus,7,2,1,2
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,1,1,5,44900,1,1,2019,...,1798,1798,17746,24.00,Skoda,Superb LK 1.8 TSI AT,7,2,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1547,2022 Maruti Ertiga VXI CNG,May-22,3,3,7,26500,1,0,2022,...,1462,1462,8663,11.50,Maruti,Ertiga VXI CNG,4,3,1,2
1495,1548,2020 Hyundai Creta SX Opt Diesel AT BSVI,Aug-20,1,2,5,35000,1,1,2020,...,11345,11345,250,17.41,Hyundai,Creta SX Opt Diesel AT BSVI,6,2,2,0
1496,1550,2017 Honda WR-V i-VTEC S,Jun-17,1,1,5,49000,1,0,2017,...,1199,1199,887,5.85,Honda,WR-V i-VTEC S,9,2,2,2
1497,1551,2018 Volkswagen Polo 1.0 MPI Comfortline,May-18,1,1,5,40000,2,0,2018,...,999,999,75,4.75,Volkswagen,Polo 1.0 MPI Comfortline,8,2,2,2
1498,1552,2018 Maruti Swift Dzire VXI,May-18,1,1,5,34756,1,0,2018,...,1197,1197,8314,6.10,Maruti,Swift Dzire VXI,8,3,2,2

In [50]:
df.drop("price(in lakhs)", axis = 1)

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),car_company,car_model,how_old,class,kms_class,engine_enc
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,1,1,5,56000,1,1,2017,7.81,2996,2996,333,Mercedes-Benz,S-Class S400,9,1,3,4
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,1,1,5,30615,1,1,2020,17.40,999,999,9863,Nissan,Magnite Turbo CVT XV Premium Opt BSVI,6,2,2,2
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,1,2,5,24000,1,1,2018,20.68,1995,1995,188,BMW,X1 sDrive 20d xLine,8,1,1,3
3,3,2019 Kia Seltos GTX Plus,Dec-19,1,1,5,18378,1,0,2019,16.50,1353,1353,13808,Kia,Seltos GTX Plus,7,2,1,2
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,1,1,5,44900,1,1,2019,14.67,1798,1798,17746,Skoda,Superb LK 1.8 TSI AT,7,2,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1547,2022 Maruti Ertiga VXI CNG,May-22,3,3,7,26500,1,0,2022,26.11,1462,1462,8663,Maruti,Ertiga VXI CNG,4,3,1,2
1495,1548,2020 Hyundai Creta SX Opt Diesel AT BSVI,Aug-20,1,2,5,35000,1,1,2020,1493.00,11345,11345,250,Hyundai,Creta SX Opt Diesel AT BSVI,6,2,2,0
1496,1550,2017 Honda WR-V i-VTEC S,Jun-17,1,1,5,49000,1,0,2017,17.50,1199,1199,887,Honda,WR-V i-VTEC S,9,2,2,2
1497,1551,2018 Volkswagen Polo 1.0 MPI Comfortline,May-18,1,1,5,40000,2,0,2018,18.78,999,999,75,Volkswagen,Polo 1.0 MPI Comfortline,8,2,2,2
1498,1552,2018 Maruti Swift Dzire VXI,May-18,1,1,5,34756,1,0,2018,20.85,1197,1197,8314,Maruti,Swift Dzire VXI,8,3,2,2

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1499 entries, 0 to 1498
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          1499 non-null   int64
 1   car_name            1499 non-null   str
 2   registration_year   1499 non-null   str
 3   insurance_validity  1499 non-null   int64
 4   fuel_type           1499 non-null   int64
 5   seats               1499 non-null   int64
 6   kms_driven          1499 non-null   int64
 7   ownsership          1499 non-null   int64
 8   transmission        1499 non-null   int64
 9   manufacturing_year  1499 non-null   int64
 10  mileage(kmpl)       1499 non-null   float64
 11  engine(cc)          1499 non-null   int64
 12  max_power(bhp)      1499 non-null   int64
 13  torque(Nm)          1499 non-null   int64
 14  price(in lakhs)     1499 non-null   float64
 15  car_company         1499 non-null   str
 16  car_model           1499 non-null   str
 17  how_old             1499 non-null   int64
 18  class               1499 non-null   int64
 19  kms_class           1499 non-null   int64
 20  engine_enc          1499 non-null   int64
dtypes: float64(2), int64(15), str(4)
memory usage: 336.9 KB

In [52]:
from sklearn.linear_model import LinearRegression

x = df[[
    "insurance_validity",
    "fuel_type",
    "seats",
    "ownsership",
    "transmission",
    "how_old",
    "class",
    "kms_class",
    "engine_enc"
]]

y = df["price(in lakhs)"]

model = LinearRegression()

model.fit(x, y)

LinearRegression()

In [81]:
model.score(x,y)

0.48237056564909764

In [53]:
from sklearn.metrics import r2_score

# Started new

In [54]:
df

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,...,engine(cc),max_power(bhp),torque(Nm),price(in lakhs),car_company,car_model,how_old,class,kms_class,engine_enc
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,1,1,5,56000,1,1,2017,...,2996,2996,333,63.75,Mercedes-Benz,S-Class S400,9,1,3,4
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,1,1,5,30615,1,1,2020,...,999,999,9863,8.99,Nissan,Magnite Turbo CVT XV Premium Opt BSVI,6,2,2,2
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,1,2,5,24000,1,1,2018,...,1995,1995,188,23.75,BMW,X1 sDrive 20d xLine,8,1,1,3
3,3,2019 Kia Seltos GTX Plus,Dec-19,1,1,5,18378,1,0,2019,...,1353,1353,13808,13.56,Kia,Seltos GTX Plus,7,2,1,2
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,1,1,5,44900,1,1,2019,...,1798,1798,17746,24.00,Skoda,Superb LK 1.8 TSI AT,7,2,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,1547,2022 Maruti Ertiga VXI CNG,May-22,3,3,7,26500,1,0,2022,...,1462,1462,8663,11.50,Maruti,Ertiga VXI CNG,4,3,1,2
1495,1548,2020 Hyundai Creta SX Opt Diesel AT BSVI,Aug-20,1,2,5,35000,1,1,2020,...,11345,11345,250,17.41,Hyundai,Creta SX Opt Diesel AT BSVI,6,2,2,0
1496,1550,2017 Honda WR-V i-VTEC S,Jun-17,1,1,5,49000,1,0,2017,...,1199,1199,887,5.85,Honda,WR-V i-VTEC S,9,2,2,2
1497,1551,2018 Volkswagen Polo 1.0 MPI Comfortline,May-18,1,1,5,40000,2,0,2018,...,999,999,75,4.75,Volkswagen,Polo 1.0 MPI Comfortline,8,2,2,2
1498,1552,2018 Maruti Swift Dzire VXI,May-18,1,1,5,34756,1,0,2018,...,1197,1197,8314,6.10,Maruti,Swift Dzire VXI,8,3,2,2

In [55]:
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_squared_error
)

In [56]:
print(df.shape)

df.info()

df.describe()

(1499, 21)
<class 'pandas.DataFrame'>
RangeIndex: 1499 entries, 0 to 1498
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          1499 non-null   int64
 1   car_name            1499 non-null   str
 2   registration_year   1499 non-null   str
 3   insurance_validity  1499 non-null   int64
 4   fuel_type           1499 non-null   int64
 5   seats               1499 non-null   int64
 6   kms_driven          1499 non-null   int64
 7   ownsership          1499 non-null   int64
 8   transmission        1499 non-null   int64
 9   manufacturing_year  1499 non-null   int64
 10  mileage(kmpl)       1499 non-null   float64
 11  engine(cc)          1499 non-null   int64
 12  max_power(bhp)      1499 non-null   int64
 13  torque(Nm)          1499 non-null   int64
 14  price(in lakhs)     1499 non-null   float64
 15  car_company         1499 non-null   str
 16  car_model           1499 non-null   str
 17  how_old             1499 non-null   int64
 18  class               1499 non-null   int64
 19  kms_class           1499 non-null   int64
 20  engine_enc          1499 non-null   int64
dtypes: float64(2), int64(15), str(4)
memory usage: 336.9 KB

,Unnamed: 0,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs),how_old,class,kms_class,engine_enc
count,1499.000000,1499.000000,1499.000000,1499.000000,1499.00000,1499.000000,1499.000000,1499.000000,1499.000000,1.499000e+03,1.499000e+03,1.499000e+03,1499.000000,1499.000000,1499.000000,1499.000000,1499.000000
mean,783.119413,1.557705,1.349566,5.206137,53219.61441,1.193462,0.444963,2017.380921,187.284703,1.521934e+10,1.521934e+10,1.274292e+04,171.506071,8.619079,2.031354,2.486324,2.207472
std,448.046260,0.897169,0.506847,0.636718,40404.02744,0.447434,0.497128,2.996381,516.597348,2.222352e+11,2.222352e+11,8.269170e+04,3540.885094,2.996381,0.693055,1.124574,0.923827
min,0.000000,1.000000,1.000000,4.000000,620.00000,1.000000,0.000000,2007.000000,7.810000,6.700000e+01,6.700000e+01,1.900000e+01,1.000000,3.000000,1.000000,1.000000,0.000000
25%,401.500000,1.000000,1.000000,5.000000,30000.00000,1.000000,0.000000,2015.000000,16.100000,1.197000e+03,1.197000e+03,5.000000e+02,4.635000,7.000000,2.000000,1.000000,2.000000
50%,791.000000,1.000000,1.000000,5.000000,49441.00000,1.000000,0.000000,2018.000000,18.760000,1.493000e+03,1.493000e+03,1.176000e+03,6.950000,8.000000,2.000000,2.000000,2.000000
75%,1168.500000,3.000000,2.000000,5.000000,70000.00000,1.000000,1.000000,2019.000000,21.400000,1.995000e+03,1.995000e+03,8.850000e+03,16.000000,11.000000,3.000000,3.000000,3.000000
max,1552.000000,3.000000,3.000000,8.000000,810000.00000,5.000000,1.000000,2023.000000,3996.000000,3.258640e+12,3.258640e+12,1.186600e+06,95000.000000,19.000000,3.000000,4.000000,4.000000

In [57]:
df.columns = df.columns.str.strip()

df = df.drop(
    columns=["Unnamed: 0"],
    errors="ignore"
)

df = df.rename(columns={
    "ownsership": "ownership"
})

print(df.columns.tolist())

['car_name', 'registration_year', 'insurance_validity', 'fuel_type', 'seats', 'kms_driven', 'ownership', 'transmission', 'manufacturing_year', 'mileage(kmpl)', 'engine(cc)', 'max_power(bhp)', 'torque(Nm)', 'price(in lakhs)', 'car_company', 'car_model', 'how_old', 'class', 'kms_class', 'engine_enc']

In [58]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 394

In [59]:
df = df.drop_duplicates().copy()

print("Shape after duplicate removal:", df.shape)

Shape after duplicate removal: (1105, 20)

In [60]:
df = df.drop_duplicates()

print(df.shape)

(1105, 20)

In [61]:
print(df.isnull().sum())

car_name              0
registration_year     0
insurance_validity    0
fuel_type             0
seats                 0
kms_driven            0
ownership             0
transmission          0
manufacturing_year    0
mileage(kmpl)         0
engine(cc)            0
max_power(bhp)        0
torque(Nm)            0
price(in lakhs)       0
car_company           0
car_model             0
how_old               0
class                 0
kms_class             0
engine_enc            0
dtype: int64

In [62]:
df = df[
    (df["price(in lakhs)"] > 0) &
    (df["price(in lakhs)"] <= 200)
].copy()

print(df.shape)

(1103, 20)

In [63]:
print(df["mileage(kmpl)"].max())
print(df["engine(cc)"].max())
print(df["max_power(bhp)"].max())
print(df["torque(Nm)"].max())

3996.0
3258640000000
3258640000000
1186600

In [64]:
df.loc[
    ~df["mileage(kmpl)"].between(1, 100),
    "mileage(kmpl)"
] = np.nan

df.loc[
    ~df["engine(cc)"].between(100, 8000),
    "engine(cc)"
] = np.nan

df.loc[
    ~df["torque(Nm)"].between(1, 3000),
    "torque(Nm)"
] = np.nan

df.loc[
    ~df["kms_driven"].between(0, 300000),
    "kms_driven"
] = np.nan

In [65]:
df = df.drop(columns=["max_power(bhp)"])

In [68]:
text_columns = [
    "car_name",
    "insurance_validity",
    "fuel_type",
    "ownership",
    "transmission"
]

for col in text_columns:
    df[col] = df[col].astype(str).str.strip()

print(df["fuel_type"].value_counts())
print(df["transmission"].value_counts())
print(df["ownership"].value_counts())

fuel_type
1    736
2    350
3     17
Name: count, dtype: int64
transmission
0    642
1    461
Name: count, dtype: int64
ownership
1    919
2    166
3     17
5      1
Name: count, dtype: int64

In [69]:
numeric_columns = [
    "seats",
    "kms_driven",
    "manufacturing_year",
    "mileage(kmpl)",
    "engine(cc)",
    "torque(Nm)"
]

for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())

In [70]:
for col in text_columns:
    df[col] = df[col].replace("nan", np.nan)
    df[col] = df[col].fillna(df[col].mode()[0])

In [71]:
current_year = pd.Timestamp.today().year

df["how_old"] = (
    current_year - df["manufacturing_year"]
)

print(
    df[["manufacturing_year", "how_old"]].head()
)

   manufacturing_year  how_old
0                2017        9
1                2020        6
2                2018        8
3                2019        7
4                2019        7

In [73]:
x = df[
    [
        "car_name",
        "insurance_validity",
        "fuel_type",
        "seats",
        "kms_driven",
        "ownership",
        "transmission",
        "manufacturing_year",
        "how_old",
        "mileage(kmpl)",
        "engine(cc)",
        "torque(Nm)"
    ]
]

y = df["price(in lakhs)"]

print(x.head())
print(y.head())

                                            car_name insurance_validity  \
0                    2017 Mercedes-Benz S-Class S400                  1
1  2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI                  1
2                       2018 BMW X1 sDrive 20d xLine                  1
3                           2019 Kia Seltos GTX Plus                  1
4                    2019 Skoda Superb LK 1.8 TSI AT                  1

  fuel_type  seats  kms_driven ownership transmission  manufacturing_year  \
0         1      5     56000.0         1            1                2017
1         1      5     30615.0         1            1                2020
2         2      5     24000.0         1            1                2018
3         1      5     18378.0         1            0                2019
4         1      5     44900.0         1            1                2019

   how_old  mileage(kmpl)  engine(cc)  torque(Nm)
0        9           7.81      2996.0       333.0
1        6          17.40       999.0       831.0
2        8          20.68      1995.0       188.0
3        7          16.50      1353.0       831.0
4        7          14.67      1798.0       831.0
0    63.75
1     8.99
2    23.75
3    13.56
4    24.00
Name: price(in lakhs), dtype: float64

In [74]:
x = pd.get_dummies(x, dtype=int)

print(x.head())
print(x.shape)

   seats  kms_driven  manufacturing_year  how_old  mileage(kmpl)  engine(cc)  \
0      5     56000.0                2017        9           7.81      2996.0
1      5     30615.0                2020        6          17.40       999.0
2      5     24000.0                2018        8          20.68      1995.0
3      5     18378.0                2019        7          16.50      1353.0
4      5     44900.0                2019        7          14.67      1798.0

   torque(Nm)  car_name_2007 Maruti SX4 Vxi BSIII  \
0       333.0                                   0
1       831.0                                   0
2       188.0                                   0
3       831.0                                   0
4       831.0                                   0

   car_name_2009 Hyundai i10 Era  car_name_2009 Hyundai i10 Era 1.1  ...  \
0                              0                                  0  ...
1                              0                                  0  ...
2                              0                                  0  ...
3                              0                                  0  ...
4                              0                                  0  ...

   insurance_validity_3  fuel_type_1  fuel_type_2  fuel_type_3  ownership_1  \
0                     0            1            0            0            1
1                     0            1            0            0            1
2                     0            0            1            0            1
3                     0            1            0            0            1
4                     0            1            0            0            1

   ownership_2  ownership_3  ownership_5  transmission_0  transmission_1
0            0            0            0               0               1
1            0            0            0               0               1
2            0            0            0               0               1
3            0            0            0               1               0
4            0            0            0               0               1

[5 rows x 921 columns]
(1103, 921)

In [75]:
X_train, X_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (882, 921)
Testing data: (221, 921)

In [76]:
model = LinearRegression()

model.fit(X_train, y_train)

print("Model training completed")

Model training completed

In [77]:
y_pred = model.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred))

print(
    "MAE:",
    mean_absolute_error(y_test, y_pred)
)

print(
    "RMSE:",
    np.sqrt(mean_squared_error(y_test, y_pred))
)

R2 Score: 0.465583629809148
MAE: 7.212602404127683
RMSE: 12.01813303702437

In [78]:
rf_model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

print("Random Forest R2:", r2_score(y_test, rf_pred))

print(
    "Random Forest MAE:",
    mean_absolute_error(y_test, rf_pred)
)

print(
    "Random Forest RMSE:",
    np.sqrt(mean_squared_error(y_test, rf_pred))
)

Random Forest R2: 0.5871670895285598
Random Forest MAE: 4.154303416289592
Random Forest RMSE: 10.562927194879888

In [79]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor()
model.fit(X_train, y_train)

KNeighborsRegressor()

In [80]:
model.score(X_train, y_train)

0.521454409982434

In [88]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)

MinMaxScaler()

In [89]:
X_scaler_train = scaler.transform(X_train)

In [90]:
model.fit(X_scaler_train, y_train)

KNeighborsRegressor()

In [91]:
model.score(X_scaler_train, y_train)

0.6985031098371721

In [92]:
X_test_scaled = scaler.transform(X_test)

In [94]:
model.score(X_test_scaled, y_test)

0.3314283142762646