# Pandas Lecture 46 — Intermediate Practice Questions

**Goal:** Practise DataFrame selection, filtering, sorting, calculated columns, renaming, and removing columns.

## How to use this notebook
1. Run the setup cell first.
2. Read each question.
3. Write your solution in the empty code cell below it.
4. Run the cell and check your output.
5. Try without looking at any solution first.

**Tip:** For multiple conditions, use `&` for AND and `|` for OR. Put each condition in parentheses.

In [1]:
import pandas as pd

data = {
    "Name": ["Tejas", "Rahul", "Amit", "Priya", "Neha", "Karan", "Sneha", "Om"],
    "Age": [21, 22, 20, 21, 23, 20, 22, 24],
    "Marks": [85, 65, 92, 45, 78, 35, 88, 72],
    "City": ["Pune", "Mumbai", "Nashik", "Pune", "Mumbai", "Nashik", "Pune", "Aurangabad"],
    "Department": ["Computer", "IT", "Computer", "ENTC", "IT", "Computer", "ENTC", "IT"],
    "Attendance": [92, 80, 96, 68, 85, 55, 91, 75]
}

df = pd.DataFrame(data)
df

    Name  Age  Marks        City Department  Attendance
0  Tejas   21     85        Pune   Computer          92
1  Rahul   22     65      Mumbai         IT          80
2   Amit   20     92      Nashik   Computer          96
3  Priya   21     45        Pune       ENTC          68
4   Neha   23     78      Mumbai         IT          85
5  Karan   20     35      Nashik   Computer          55
6  Sneha   22     88        Pune       ENTC          91
7     Om   24     72  Aurangabad         IT          75

## Q1 — Filter by marks

Display only students who scored more than 75 marks.

In [3]:
# Write your solution below
df[df['Marks'] > 75]

    Name  Age  Marks    City Department  Attendance
0  Tejas   21     85    Pune   Computer          92
2   Amit   20     92  Nashik   Computer          96
4   Neha   23     78  Mumbai         IT          85
6  Sneha   22     88    Pune       ENTC          91

## Q2 — Filter by age

Display students whose age is 21 or above.

In [5]:
# Write your solution below
df[df['Age'] >= 21]

    Name  Age  Marks        City Department  Attendance
0  Tejas   21     85        Pune   Computer          92
1  Rahul   22     65      Mumbai         IT          80
3  Priya   21     45        Pune       ENTC          68
4   Neha   23     78      Mumbai         IT          85
6  Sneha   22     88        Pune       ENTC          91
7     Om   24     72  Aurangabad         IT          75

## Q3 — Filter by city

Display only students from Pune.

In [6]:
# Write your solution below
df[df["City"]=="Pune"]

    Name  Age  Marks  City Department  Attendance
0  Tejas   21     85  Pune   Computer          92
3  Priya   21     45  Pune       ENTC          68
6  Sneha   22     88  Pune       ENTC          91

## Q4 — OR condition

Display students from Pune OR Mumbai.

In [9]:
# Write your solution below
df[(df["City"] == "Pune") | (df["City"] == "Mumbai")]

    Name  Age  Marks    City Department  Attendance
0  Tejas   21     85    Pune   Computer          92
1  Rahul   22     65  Mumbai         IT          80
3  Priya   21     45    Pune       ENTC          68
4   Neha   23     78  Mumbai         IT          85
6  Sneha   22     88    Pune       ENTC          91

## Q5 — AND condition

Display students who scored more than 70 AND have attendance of at least 80.

In [11]:
# Write your solution below
df[(df["Marks"] > 70) & (df["Attendance"] >= 80)]

    Name  Age  Marks    City Department  Attendance
0  Tejas   21     85    Pune   Computer          92
2   Amit   20     92  Nashik   Computer          96
4   Neha   23     78  Mumbai         IT          85
6  Sneha   22     88    Pune       ENTC          91

## Q6 — Multiple conditions

Display students who are in the Computer department AND scored at least 80 marks.

In [12]:
# Write your solution below
df[(df["Department"] == "Computer") & (df["Marks"] >= 80)]

    Name  Age  Marks    City Department  Attendance
0  Tejas   21     85    Pune   Computer          92
2   Amit   20     92  Nashik   Computer          96

## Q7 — Select chosen columns

Display only Name, Department, and Marks for students who scored at least 75.

In [16]:
# Write your solution below
df[df["Marks"] >= 75][["Name","Department","Marks"]]

    Name Department  Marks
0  Tejas   Computer     85
2   Amit   Computer     92
4   Neha         IT     78
6  Sneha       ENTC     88

## Q8 — Sort descending

Sort the complete DataFrame by Marks from highest to lowest.

In [33]:
# Write your solution below
# df[df["Marks"].sort_values(ascending=False)]
df.sort_values(by='Marks', ascending=False)

    Name  Age  Marks        City Department  Attendance
2   Amit   20     92      Nashik   Computer          96
6  Sneha   22     88        Pune       ENTC          91
0  Tejas   21     85        Pune   Computer          92
4   Neha   23     78      Mumbai         IT          85
7     Om   24     72  Aurangabad         IT          75
1  Rahul   22     65      Mumbai         IT          80
3  Priya   21     45        Pune       ENTC          68
5  Karan   20     35      Nashik   Computer          55

## Q9 — Sort by two columns

Sort by Department first, then by Marks from highest to lowest within each department.

In [35]:
# Write your solution below
df.sort_values(by = "Department").sort_values(by = "Marks",ascending=False)

    Name  Age  Marks        City Department  Attendance
2   Amit   20     92      Nashik   Computer          96
6  Sneha   22     88        Pune       ENTC          91
0  Tejas   21     85        Pune   Computer          92
4   Neha   23     78      Mumbai         IT          85
7     Om   24     72  Aurangabad         IT          75
1  Rahul   22     65      Mumbai         IT          80
3  Priya   21     45        Pune       ENTC          68
5  Karan   20     35      Nashik   Computer          55

## Q10 — Add a calculated column

Create a new column BonusMarks by adding 5 to each student's Marks. Keep the original Marks column.

In [38]:
# Write your solution below
df["BonusMarks"] = df["Marks"] + 5
df

    Name  Age  Marks        City Department  Attendance  BonusMarks
0  Tejas   21     85        Pune   Computer          92          90
1  Rahul   22     65      Mumbai         IT          80          70
2   Amit   20     92      Nashik   Computer          96          97
3  Priya   21     45        Pune       ENTC          68          50
4   Neha   23     78      Mumbai         IT          85          83
5  Karan   20     35      Nashik   Computer          55          40
6  Sneha   22     88        Pune       ENTC          91          93
7     Om   24     72  Aurangabad         IT          75          77

## Q11 — Add a result column

Create a column Result containing 'Pass' if Marks are at least 40, otherwise 'Fail'. Use a beginner-friendly method you know.

In [7]:
# Write your solution below
df["Result"] = df["Marks"].apply(lambda x : "Pass" if x >= 40 else "Fail")
df

    Name  Age  Marks        City Department  Attendance Result
0  Tejas   21     85        Pune   Computer          92   Pass
1  Rahul   22     65      Mumbai         IT          80   Pass
2   Amit   20     92      Nashik   Computer          96   Pass
3  Priya   21     45        Pune       ENTC          68   Pass
4   Neha   23     78      Mumbai         IT          85   Pass
5  Karan   20     35      Nashik   Computer          55   Fail
6  Sneha   22     88        Pune       ENTC          91   Pass
7     Om   24     72  Aurangabad         IT          75   Pass

## Q12 — Rename a column

Rename Attendance to AttendancePercent and display the column names.

In [13]:
# Write your solution below
df.rename(columns = {"Attendance": "AttendancePercent"},inplace=True)
df.columns

Index(['Name', 'Age', 'Marks', 'City', 'Department', 'AttendancePercent',
       'Result'],
      dtype='str')

## Q13 — Remove a column

Create a DataFrame without the Age column. Do not modify the original df.

In [17]:
# Write your solution below
df_1 = df[['Name','Marks','City','Department']]
df_1

    Name  Marks        City Department
0  Tejas     85        Pune   Computer
1  Rahul     65      Mumbai         IT
2   Amit     92      Nashik   Computer
3  Priya     45        Pune       ENTC
4   Neha     78      Mumbai         IT
5  Karan     35      Nashik   Computer
6  Sneha     88        Pune       ENTC
7     Om     72  Aurangabad         IT

## Q14 — Range filter

Display students whose Marks are between 60 and 90, including 60 and 90.

In [19]:
# Write your solution below
df[df["Marks"].between(60,90)]

    Name  Age  Marks        City Department  AttendancePercent Result
0  Tejas   21     85        Pune   Computer                 92   Pass
1  Rahul   22     65      Mumbai         IT                 80   Pass
4   Neha   23     78      Mumbai         IT                 85   Pass
6  Sneha   22     88        Pune       ENTC                 91   Pass
7     Om   24     72  Aurangabad         IT                 75   Pass

## Q15 — Membership filter

Display students whose Department is either IT or ENTC.

In [21]:
# Write your solution below
df[df["Department"].isin(["IT","ENTC"])]

    Name  Age  Marks        City Department  AttendancePercent Result
1  Rahul   22     65      Mumbai         IT                 80   Pass
3  Priya   21     45        Pune       ENTC                 68   Pass
4   Neha   23     78      Mumbai         IT                 85   Pass
6  Sneha   22     88        Pune       ENTC                 91   Pass
7     Om   24     72  Aurangabad         IT                 75   Pass

## Q16 — Combined challenge

Display Name, City, Marks, and Attendance only for students from Pune or Mumbai who scored at least 75 marks AND have attendance of at least 80.

In [38]:
# Write your solution below
a = df["City"].isin(["Pune","Mumbai"]) 
b = df["Marks"] >= 75
c = df["AttendancePercent"] >= 80
df[a & b & c]

    Name  Age  Marks    City Department  AttendancePercent Result
0  Tejas   21     85    Pune   Computer                 92   Pass
4   Neha   23     78  Mumbai         IT                 85   Pass
6  Sneha   22     88    Pune       ENTC                 91   Pass

## Final Challenge — Employee DataFrame

Create a DataFrame with at least 8 employees and these columns:

- `EmployeeID`
- `Name`
- `Department`
- `Salary`
- `Experience`
- `City`

Then solve these tasks in code cells below:

1. Display the first five employees.
2. Find employees earning more than ₹40,000.
3. Find employees with more than three years of experience.
4. Calculate the average salary.
5. Display employees in IT with salary above ₹40,000.
6. Sort employees by salary from highest to lowest.
7. Add `AnnualSalary` = `Salary * 12`.
8. Display only Name, Department, and AnnualSalary for employees with more than three years of experience.

Create your own realistic sample data.

In [40]:
# Create your employee DataFrame here
data = {
    "EmployeeID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Hank"],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing", "Finance", "HR", "Marketing"],
    "Salary": [50000, 65000, 70000, 72000, 55000, 68000, 52000, 60000],
    "Experience": [3, 5, 7, 6, 4, 8, 2, 5],  # in years
    "City": ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Pune", "Chennai", "Kolkata", "Ahmedabad"]
}
df = pd.DataFrame(data)
df

   EmployeeID     Name Department  Salary  Experience       City
0         101    Alice         HR   50000           3     Mumbai
1         102      Bob         IT   65000           5      Delhi
2         103  Charlie    Finance   70000           7  Bangalore
3         104    David         IT   72000           6  Hyderabad
4         105      Eva  Marketing   55000           4       Pune
5         106    Frank    Finance   68000           8    Chennai
6         107    Grace         HR   52000           2    Kolkata
7         108     Hank  Marketing   60000           5  Ahmedabad

In [41]:
df.head()

   EmployeeID     Name Department  Salary  Experience       City
0         101    Alice         HR   50000           3     Mumbai
1         102      Bob         IT   65000           5      Delhi
2         103  Charlie    Finance   70000           7  Bangalore
3         104    David         IT   72000           6  Hyderabad
4         105      Eva  Marketing   55000           4       Pune

In [43]:
df[df["Salary"] > 40000]

   EmployeeID     Name Department  Salary  Experience       City
0         101    Alice         HR   50000           3     Mumbai
1         102      Bob         IT   65000           5      Delhi
2         103  Charlie    Finance   70000           7  Bangalore
3         104    David         IT   72000           6  Hyderabad
4         105      Eva  Marketing   55000           4       Pune
5         106    Frank    Finance   68000           8    Chennai
6         107    Grace         HR   52000           2    Kolkata
7         108     Hank  Marketing   60000           5  Ahmedabad

In [44]:
df[df["Experience"] > 3]

   EmployeeID     Name Department  Salary  Experience       City
1         102      Bob         IT   65000           5      Delhi
2         103  Charlie    Finance   70000           7  Bangalore
3         104    David         IT   72000           6  Hyderabad
4         105      Eva  Marketing   55000           4       Pune
5         106    Frank    Finance   68000           8    Chennai
7         108     Hank  Marketing   60000           5  Ahmedabad

In [50]:
df["Salary"].mean()

np.float64(61500.0)

In [51]:
df[(df["Department"] == "IT")&(df["Salary"] > 40000)]

   EmployeeID   Name Department  Salary  Experience       City
1         102    Bob         IT   65000           5      Delhi
3         104  David         IT   72000           6  Hyderabad

In [52]:
df.sort_values(by = "Salary",ascending=False)

   EmployeeID     Name Department  Salary  Experience       City
3         104    David         IT   72000           6  Hyderabad
2         103  Charlie    Finance   70000           7  Bangalore
5         106    Frank    Finance   68000           8    Chennai
1         102      Bob         IT   65000           5      Delhi
7         108     Hank  Marketing   60000           5  Ahmedabad
4         105      Eva  Marketing   55000           4       Pune
6         107    Grace         HR   52000           2    Kolkata
0         101    Alice         HR   50000           3     Mumbai

In [54]:
df["Anual_sal"] = df["Salary"] * 12
df

   EmployeeID     Name Department  Salary  Experience       City  Anual_sal
0         101    Alice         HR   50000           3     Mumbai     600000
1         102      Bob         IT   65000           5      Delhi     780000
2         103  Charlie    Finance   70000           7  Bangalore     840000
3         104    David         IT   72000           6  Hyderabad     864000
4         105      Eva  Marketing   55000           4       Pune     660000
5         106    Frank    Finance   68000           8    Chennai     816000
6         107    Grace         HR   52000           2    Kolkata     624000
7         108     Hank  Marketing   60000           5  Ahmedabad     720000

In [55]:
df[df["Experience"] > 3][["Name","Department","Anual_sal"]]

      Name Department  Anual_sal
1      Bob         IT     780000
2  Charlie    Finance     840000
3    David         IT     864000
4      Eva  Marketing     660000
5    Frank    Finance     816000
7     Hank  Marketing     720000

## Self-check checklist

- [ ] I can select one or multiple columns.
- [ ] I can filter rows using one condition.
- [ ] I can combine conditions with `&` and `|`.
- [ ] I remember parentheses around each condition.
- [ ] I can sort by one or more columns.
- [ ] I can add calculated columns.
- [ ] I can rename and remove columns.
- [ ] I can solve the employee challenge without copying an example.

**Next lesson:** Lecture 47 — Pandas Filtering and Conditional Selection in Depth.