In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Tejas Gaikwad\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Tejas Gaikwad\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Tejas Gaikwad\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Tejas Gaikwad\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 1.2 MB/s eta 0:00:08
   --- ------------------------------------ 0.8/9.8 MB 1.2 MB/s eta 0:00:08
   ---- ----------------------------------- 1.0/9.8 MB 1.3 MB/s eta 0:00:07
   ----- ---------------------------------- 1.3/9.8 MB 1.3 MB/s eta 0:00:07
   ------- -------------------------------- 1.8/9.8 MB 1.5 MB/s eta 0:00:06
   -------- ------------------------------- 2.1/9.8 MB 1.5 MB/s eta 0:00:06
   ---------- ----------------------------- 2.6/9.8 MB 1.6 MB/s eta 0:00:05
   ----------- ---------------------------- 2.9/9.8 MB 1.6 MB/s eta 0:00:05
   ------------- -------------------------- 3.4/9.8 MB 1.7 MB/s eta 0:00:04
   -------------- ------------------------- 3.7/9.8 MB 1.7 MB/s eta 0:00:04
   ---------------- ----------------------- 3.9/9.8 MB 1.6 MB/s eta 0:00:04
   ----------------- ---------------------- 4.2/9.8 MB 1.6 MB/s eta 0:00:04
   ------------------ --------------------- 4.5/9.8 MB 1.6 MB/s eta 0:00:04
   -------------------- ------------------- 5.0/9.8 MB 1.6 MB/s eta 0:00:04
   --------------------- ------------------ 5.2/9.8 MB 1.6 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.8 MB 1.6 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.8 MB 1.6 MB/s eta 0:00:03
   ------------------------- -------------- 6.3/9.8 MB 1.6 MB/s eta 0:00:03
   --------------------------- ------------ 6.8/9.8 MB 1.6 MB/s eta 0:00:02
   ---------------------------- ----------- 7.1/9.8 MB 1.6 MB/s eta 0:00:02
   ------------------------------- -------- 7.6/9.8 MB 1.7 MB/s eta 0:00:02
   --------------------------------- ------ 8.1/9.8 MB 1.7 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.8 MB 1.8 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 1.8 MB/s  0:00:05
Installing collected packages: pandas
Successfully installed pandas-3.0.6

In [1]:
import pandas as pd
import numpy as np

In [3]:
d1 = {'e_id':[101,102,103,104,105],
      'e_name':['amol','amit','akash','avinash','atish'],
      'e_sal':[25000,17500.5,55000,82000,42200.1],
      'e_dept':['HR','HR','IT','IT','IT']}
df = pd.DataFrame(d1,index=['A','B','C','X','Y'])
df

   e_id   e_name    e_sal e_dept
A   101     amol  25000.0     HR
B   102     amit  17500.5     HR
C   103    akash  55000.0     IT
X   104  avinash  82000.0     IT
Y   105    atish  42200.1     IT

# iloc() is gives actual content of that index

In [4]:
df.iloc[3,2] #gives the value at that index

np.float64(82000.0)

In [6]:
#and we can update values also
df.iloc[3,2] = 6700
df

   e_id   e_name    e_sal e_dept
A   101     amol  25000.0     HR
B   102     amit  17500.5     HR
C   103    akash  55000.0     IT
X   104  avinash   6700.0     IT
Y   105    atish  42200.1     IT

In [7]:
df['e_sal'].mean()

np.float64(29280.120000000003)

In [9]:
df.iloc[2:,:2] #rows and column

   e_id   e_name
C   103    akash
X   104  avinash
Y   105    atish

In [10]:
print(df)

   e_id   e_name    e_sal e_dept
A   101     amol  25000.0     HR
B   102     amit  17500.5     HR
C   103    akash  55000.0     IT
X   104  avinash   6700.0     IT
Y   105    atish  42200.1     IT

# .loc() gives the row series

In [14]:
df.loc['A']

e_id          101
e_name       amol
e_sal     25000.0
e_dept         HR
Name: A, dtype: object

In [15]:
df

   e_id   e_name    e_sal e_dept
A   101     amol  25000.0     HR
B   102     amit  17500.5     HR
C   103    akash  55000.0     IT
X   104  avinash   6700.0     IT
Y   105    atish  42200.1     IT

In [18]:
df['e_dept'] == 'IT'

A    False
B    False
C     True
X     True
Y     True
Name: e_dept, dtype: bool

In [19]:
#data of employee of IT department
df[df['e_dept'] == 'IT']

   e_id   e_name    e_sal e_dept
C   103    akash  55000.0     IT
X   104  avinash   6700.0     IT
Y   105    atish  42200.1     IT

In [20]:
#we need only salary
df[df['e_dept'] == 'IT']['e_sal']

C    55000.0
X     6700.0
Y    42200.1
Name: e_sal, dtype: float64

In [21]:
#mean of salary
df[df['e_dept'] == 'IT']['e_sal'].mean()

np.float64(34633.36666666667)

#### count of employeee more than 50K salary

In [23]:
df['e_sal'] > 50000

A    False
B    False
C     True
X    False
Y    False
Name: e_sal, dtype: bool

In [24]:
sum(df['e_sal'] > 50000)

1

#### Max Salary from HR Dept

In [25]:
df['e_dept'] == 'HR'

A     True
B     True
C    False
X    False
Y    False
Name: e_dept, dtype: bool

In [26]:
df[df['e_dept'] == 'HR']['e_sal']

A    25000.0
B    17500.5
Name: e_sal, dtype: float64

In [27]:
max(df[df['e_dept'] == 'HR']['e_sal'])

25000.0

#### How many emp from "IT" dept getting less than 60K

In [28]:
df[df['e_dept'] == 'IT']['e_sal']

C    55000.0
X     6700.0
Y    42200.1
Name: e_sal, dtype: float64

In [29]:
df[df['e_dept'] == 'IT']['e_sal'] > 60000

C    False
X    False
Y    False
Name: e_sal, dtype: bool

In [30]:
sum(df[df['e_dept'] == 'IT']['e_sal'] > 60000)

0

#### Name of emp who has highest salary

In [36]:
df['e_sal'].max()

np.float64(55000.0)

In [38]:
max(df['e_sal'])

55000.0

In [39]:
df[df['e_sal'] == df['e_sal'].max()]

   e_id e_name    e_sal e_dept
C   103  akash  55000.0     IT

In [40]:
df[df['e_sal'] == df['e_sal'].max()]['e_name']

C    akash
Name: e_name, dtype: str

In [4]:
df[df['e_sal'] == df['e_sal'].max()]['e_name'].iloc[0] #if we only want the name

'avinash'

In [5]:
df[df['e_sal'] == df['e_sal'].min()]['e_name'].iloc[0]

'amit'

In [6]:
df['e_name'].min()#alphabetical order

'akash'

## Reading data from diffrent files --> Excel,sql,csv,...

In [3]:
df = pd.read_excel('stud_db.xlsx')

In [3]:
df

   Roll Name  Marks Address  Dept
0     1   qw     76    Pune     1
1     2   df     45  Mumbai     1
2     3   vc     56  Nagpur     1
3     4   bn     78    Pune     2
4     5   hj     74  Mumbai     2
5     6   yu     49  Nagpur     2
6     7   fg     68    Pune     2
7     8   tr     84  Mumbai     1

In [4]:
# 1) find avg marks from pune,mumbai,nagpur
df['Address'] == 'Pune'

0     True
1    False
2    False
3     True
4    False
5    False
6     True
7    False
Name: Address, dtype: bool

In [8]:
df[df['Address'] == 'Pune']['Marks']

0    76
3    78
6    68
Name: Marks, dtype: int64

In [9]:
df[df['Address'] == 'Pune']['Marks'].mean()

np.float64(74.0)

In [10]:
df[df['Address'] == 'Mumbai']['Marks'].mean()

np.float64(67.66666666666667)

In [11]:
df[df['Address'] == 'Nagpur']['Marks'].mean()

np.float64(52.5)

In [12]:
#2) find count of failed stdents from mumbai pass >= 50
df[df['Address'] == 'Mumbai']['Marks']

1    45
4    74
7    84
Name: Marks, dtype: int64

In [13]:
df[df['Address'] == 'Mumbai']['Marks'] <= 50

1     True
4    False
7    False
Name: Marks, dtype: bool

In [14]:
sum(df[df['Address'] == 'Mumbai']['Marks'] <= 50)

1

In [15]:
#3)find name of topper
df['Marks'].max()

np.int64(84)

In [16]:
df['Marks'].max() == df['Marks']

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
Name: Marks, dtype: bool

In [17]:
df[df['Marks'].max() == df['Marks']]

   Roll Name  Marks Address  Dept
7     8   tr     84  Mumbai     1

In [20]:
df[df['Marks'].max() == df['Marks']]['Name']

7    tr
Name: Name, dtype: str

In [21]:
df[df['Marks'].max() == df['Marks']]['Name'].iloc[0]

'tr'

In [23]:
#4)find topper marks from dept 2
df[df['Dept'] == 2]

   Roll Name  Marks Address  Dept
3     4   bn     78    Pune     2
4     5   hj     74  Mumbai     2
5     6   yu     49  Nagpur     2
6     7   fg     68    Pune     2

In [24]:
df[df['Dept'] == 2]['Marks']

3    78
4    74
5    49
6    68
Name: Marks, dtype: int64

In [39]:
df[df['Dept'] == 2]['Marks'].max()

np.int64(78)

In [26]:
print(df[df['Dept'] == 2]['Marks'].max())

78

In [4]:
#If we want to many columns so we use data in list at the end
df[df['Marks'] == df[df['Dept'] == 2]['Marks'].max()][['Name','Marks']]

  Name  Marks
3   bn     78

## Series Funtions

## 1) .unique()

In [42]:
df['Address'].unique() # Gives the unique value from data

<ArrowStringArray>
['Pune', 'Mumbai', 'Nagpur']
Length: 3, dtype: str

## 2) .nunique()

In [45]:
df['Address'].nunique() #total of unique value

3

## 3) .value_counts()

In [47]:
df['Address'].value_counts() #tells the count of unique values elements

Address
Pune      3
Mumbai    3
Nagpur    2
Name: count, dtype: int64

## 4) .appy()

In [49]:
df['Address'].apply(lambda x : x[:2]) #like we use map in list we use appy in series

0    Pu
1    Mu
2    Na
3    Pu
4    Mu
5    Na
6    Pu
7    Mu
Name: Address, dtype: str

In [51]:
df['Address'].apply(lambda x : x[0] + x[-1])

0    Pe
1    Mi
2    Nr
3    Pe
4    Mi
5    Nr
6    Pe
7    Mi
Name: Address, dtype: str

In [56]:
np.where(df['Marks'] >= 50, df['Marks'] + 5, df['Marks'] + 10)

array([81, 55, 61, 83, 79, 59, 73, 89])

In [58]:
df['Marks'].apply(lambda x : x+ 10 if x <= 50 else x + 5)

0    81
1    55
2    61
3    83
4    79
5    59
6    73
7    89
Name: Marks, dtype: int64

## DATAFRAME funtions

## 1) .groupby()

In [4]:
#groupby working in background it works like 
df.groupby('Address') #basically it is series means iterable object we can access it by the for loop

In [5]:
for i in df.groupby('Address'):
    print(i)

('Mumbai',    Roll Name  Marks Address  Dept
1     2   df     45  Mumbai     1
4     5   hj     74  Mumbai     2
7     8   tr     84  Mumbai     1)
('Nagpur',    Roll Name  Marks Address  Dept
2     3   vc     56  Nagpur     1
5     6   yu     49  Nagpur     2)
('Pune',    Roll Name  Marks Address  Dept
0     1   qw     76    Pune     1
3     4   bn     78    Pune     2
6     7   fg     68    Pune     2)

In [6]:
for i,j in df.groupby('Address'):  #here i is key that is address and the j is the values
    print(i)

Mumbai
Nagpur
Pune

In [7]:
for i,j in df.groupby('Address'):  
    print(j) #here we actualy got the values

   Roll Name  Marks Address  Dept
1     2   df     45  Mumbai     1
4     5   hj     74  Mumbai     2
7     8   tr     84  Mumbai     1
   Roll Name  Marks Address  Dept
2     3   vc     56  Nagpur     1
5     6   yu     49  Nagpur     2
   Roll Name  Marks Address  Dept
0     1   qw     76    Pune     1
3     4   bn     78    Pune     2
6     7   fg     68    Pune     2

In [8]:
# If we need the only values we use the like that
for i,j in df.groupby('Address')['Marks']:  
    print(i,j)

Mumbai 1    45
4    74
7    84
Name: Marks, dtype: int64
Nagpur 2    56
5    49
Name: Marks, dtype: int64
Pune 0    76
3    78
6    68
Name: Marks, dtype: int64

### we have to find the avg of each city ?

In [12]:
df.groupby('Address')['Marks'] #it gives the Iterable object values

In [13]:
df.groupby('Address')['Marks'].mean()

Address
Mumbai    67.666667
Nagpur    52.500000
Pune      74.000000
Name: Marks, dtype: float64

### Dept - wise topper marks

In [15]:
df.groupby('Dept')['Marks'].max()

Dept
1    84
2    78
Name: Marks, dtype: int64

In [2]:
df_stud = pd.read_excel("stud_db.xlsx")
df_stud

   Roll Name  Marks Address  Dept
0     1   qw     76    Pune     1
1     2   df     45  Mumbai     1
2     3   vc     56  Nagpur     1
3     4   bn     78    Pune     2
4     5   hj     74  Mumbai     2
5     6   yu     49  Nagpur     2
6     7   fg     68    Pune     2
7     8   tr     84  Mumbai     1

In [3]:
df_depts = pd.read_excel("stud_db.xlsx",sheet_name = "Depts")
df_depts

   dept_id          Name  HOD
0        1  Comp Science  XYZ
1        2    Statistics  PQR
2        3         Maths  MNO

# Maximum marks from name = Statistics

In [5]:
df_depts["Name"] == "Statistics"

0    False
1     True
2    False
Name: Name, dtype: bool

In [7]:
df_depts[df_depts["Name"] == "Statistics"]["dept_id"].iloc[0]

np.int64(2)

In [8]:
df_stud[df_stud["Dept"] == df_depts[df_depts["Name"] == "Statistics"]["dept_id"].iloc[0]]

   Roll Name  Marks Address  Dept
3     4   bn     78    Pune     2
4     5   hj     74  Mumbai     2
5     6   yu     49  Nagpur     2
6     7   fg     68    Pune     2

In [9]:
df_stud[df_stud["Dept"] == df_depts[df_depts["Name"] == "Statistics"]["dept_id"].iloc[0]]["Marks"].max()

np.int64(78)

In [10]:
print(df_stud[df_stud["Dept"] == df_depts[df_depts["Name"] == "Statistics"]["dept_id"].iloc[0]]["Marks"].max())

78

# Find out HOD's name of student vc

In [14]:
df_stud["Name"] == "vc"

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7    False
Name: Name, dtype: bool

In [15]:
df_stud[df_stud["Name"] == "vc"]["Dept"]

2    1
Name: Dept, dtype: int64

In [16]:
df_stud[df_stud["Name"] == "vc"]["Dept"].iloc[0]

np.int64(1)

In [18]:
df_depts["dept_id"] == df_stud[df_stud["Name"] == "vc"]["Dept"].iloc[0]

0     True
1    False
2    False
Name: dept_id, dtype: bool

In [19]:
df_depts[df_depts["dept_id"] == df_stud[df_stud["Name"] == "vc"]["Dept"].iloc[0]]["HOD"]

0    XYZ
Name: HOD, dtype: str

In [23]:
print(df_depts[df_depts["dept_id"] == df_stud[df_stud["Name"] == "vc"]["Dept"].iloc[0]]["HOD"].iloc[0])

XYZ

# **Merge Two datasets by using merge**

In [4]:
df_merge = pd.merge(df_stud,df_depts,left_on="Dept",right_on = "dept_id")
df_merge

   Roll Name_x  Marks Address  Dept  dept_id        Name_y  HOD
0     1     qw     76    Pune     1        1  Comp Science  XYZ
1     2     df     45  Mumbai     1        1  Comp Science  XYZ
2     3     vc     56  Nagpur     1        1  Comp Science  XYZ
3     4     bn     78    Pune     2        2    Statistics  PQR
4     5     hj     74  Mumbai     2        2    Statistics  PQR
5     6     yu     49  Nagpur     2        2    Statistics  PQR
6     7     fg     68    Pune     2        2    Statistics  PQR
7     8     tr     84  Mumbai     1        1  Comp Science  XYZ

# Maximum marks from name = Statistics

In [9]:
df_merge["Name_y"] == "Statistics"

0    False
1    False
2    False
3     True
4     True
5     True
6     True
7    False
Name: Name_y, dtype: bool

In [10]:
df_merge[df_merge["Name_y"] == "Statistics"]

   Roll Name_x  Marks Address  Dept  dept_id      Name_y  HOD
3     4     bn     78    Pune     2        2  Statistics  PQR
4     5     hj     74  Mumbai     2        2  Statistics  PQR
5     6     yu     49  Nagpur     2        2  Statistics  PQR
6     7     fg     68    Pune     2        2  Statistics  PQR

In [11]:
df_merge[df_merge["Name_y"] == "Statistics"]["Marks"]

3    78
4    74
5    49
6    68
Name: Marks, dtype: int64

In [12]:
df_merge[df_merge["Name_y"] == "Statistics"]["Marks"].max()

np.int64(78)

In [14]:
max(df_merge[df_merge["Name_y"] == "Statistics"]["Marks"])

78

# Find out HOD's name of student vc

In [5]:
df_merge['Name_x'] == 'vc'

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7    False
Name: Name_x, dtype: bool

In [6]:
df_merge[df_merge['Name_x'] == 'vc']

   Roll Name_x  Marks Address  Dept  dept_id        Name_y  HOD
2     3     vc     56  Nagpur     1        1  Comp Science  XYZ

In [7]:
df_merge[df_merge['Name_x'] == 'vc']['HOD']

2    XYZ
Name: HOD, dtype: str

In [8]:
df_merge[df_merge['Name_x'] == 'vc']['HOD'].iloc[0]

'XYZ'

# Joins

### 1)Inner 2)Left 3)right 4)outer join

In [15]:
pd.merge(df_stud,df_depts,left_on="Dept",right_on = "dept_id",how = "inner")

   Roll Name_x  Marks Address  Dept  dept_id        Name_y  HOD
0     1     qw     76    Pune     1        1  Comp Science  XYZ
1     2     df     45  Mumbai     1        1  Comp Science  XYZ
2     3     vc     56  Nagpur     1        1  Comp Science  XYZ
3     4     bn     78    Pune     2        2    Statistics  PQR
4     5     hj     74  Mumbai     2        2    Statistics  PQR
5     6     yu     49  Nagpur     2        2    Statistics  PQR
6     7     fg     68    Pune     2        2    Statistics  PQR
7     8     tr     84  Mumbai     1        1  Comp Science  XYZ

In [16]:
pd.merge(df_stud,df_depts,left_on="Dept",right_on = "dept_id",how = "left")

   Roll Name_x  Marks Address  Dept  dept_id        Name_y  HOD
0     1     qw     76    Pune     1        1  Comp Science  XYZ
1     2     df     45  Mumbai     1        1  Comp Science  XYZ
2     3     vc     56  Nagpur     1        1  Comp Science  XYZ
3     4     bn     78    Pune     2        2    Statistics  PQR
4     5     hj     74  Mumbai     2        2    Statistics  PQR
5     6     yu     49  Nagpur     2        2    Statistics  PQR
6     7     fg     68    Pune     2        2    Statistics  PQR
7     8     tr     84  Mumbai     1        1  Comp Science  XYZ

In [17]:
pd.merge(df_stud,df_depts,left_on="Dept",right_on = "dept_id",how = "right")

   Roll Name_x  Marks Address  Dept  dept_id        Name_y  HOD
0   1.0     qw   76.0    Pune   1.0        1  Comp Science  XYZ
1   2.0     df   45.0  Mumbai   1.0        1  Comp Science  XYZ
2   3.0     vc   56.0  Nagpur   1.0        1  Comp Science  XYZ
3   8.0     tr   84.0  Mumbai   1.0        1  Comp Science  XYZ
4   4.0     bn   78.0    Pune   2.0        2    Statistics  PQR
5   5.0     hj   74.0  Mumbai   2.0        2    Statistics  PQR
6   6.0     yu   49.0  Nagpur   2.0        2    Statistics  PQR
7   7.0     fg   68.0    Pune   2.0        2    Statistics  PQR
8   NaN    NaN    NaN     NaN   NaN        3         Maths  MNO

In [18]:
pd.merge(df_stud,df_depts,left_on="Dept",right_on = "dept_id",how = "outer") #dept coluluumn becomes the float beacuse the normally NaN is float so integer is converted in the float & others str is upper in the type castig

   Roll Name_x  Marks Address  Dept  dept_id        Name_y  HOD
0   1.0     qw   76.0    Pune   1.0        1  Comp Science  XYZ
1   2.0     df   45.0  Mumbai   1.0        1  Comp Science  XYZ
2   3.0     vc   56.0  Nagpur   1.0        1  Comp Science  XYZ
3   8.0     tr   84.0  Mumbai   1.0        1  Comp Science  XYZ
4   4.0     bn   78.0    Pune   2.0        2    Statistics  PQR
5   5.0     hj   74.0  Mumbai   2.0        2    Statistics  PQR
6   6.0     yu   49.0  Nagpur   2.0        2    Statistics  PQR
7   7.0     fg   68.0    Pune   2.0        2    Statistics  PQR
8   NaN    NaN    NaN     NaN   NaN        3         Maths  MNO

# .sorted_values("Column_name")

In [8]:
df1 = pd.merge(df_stud,df_depts,left_on="Dept",right_on = "dept_id")
df1.sort_values('Marks')

   Roll Name_x  Marks Address  Dept  dept_id        Name_y  HOD
1     2     df     45  Mumbai     1        1  Comp Science  XYZ
5     6     yu     49  Nagpur     2        2    Statistics  PQR
2     3     vc     56  Nagpur     1        1  Comp Science  XYZ
6     7     fg     68    Pune     2        2    Statistics  PQR
4     5     hj     74  Mumbai     2        2    Statistics  PQR
0     1     qw     76    Pune     1        1  Comp Science  XYZ
3     4     bn     78    Pune     2        2    Statistics  PQR
7     8     tr     84  Mumbai     1        1  Comp Science  XYZ

In [11]:
df1.sort_values('Marks',ascending = False)

   Roll Name_x  Marks Address  Dept  dept_id        Name_y  HOD
7     8     tr     84  Mumbai     1        1  Comp Science  XYZ
3     4     bn     78    Pune     2        2    Statistics  PQR
0     1     qw     76    Pune     1        1  Comp Science  XYZ
4     5     hj     74  Mumbai     2        2    Statistics  PQR
6     7     fg     68    Pune     2        2    Statistics  PQR
2     3     vc     56  Nagpur     1        1  Comp Science  XYZ
5     6     yu     49  Nagpur     2        2    Statistics  PQR
1     2     df     45  Mumbai     1        1  Comp Science  XYZ

### Merge can be done with only two dataset at a time but conacate done with many dataset
### Concate done vertically - have clumn same 
### Concate done with many datasets

In [12]:
df1 = pd.DataFrame({
    'Name': ['Amit', 'Rahul'],
    'Age': [20, 21]
})

df2 = pd.DataFrame({
    'Name': ['Sneha', 'Priya'],
    'Age': [22, 23]
})

result = pd.concat([df1, df2])

print(result)

    Name  Age
0   Amit   20
1  Rahul   21
0  Sneha   22
1  Priya   23

In [14]:
result = pd.concat([df1, df2], ignore_index=True)
print(result)

    Name  Age
0   Amit   20
1  Rahul   21
2  Sneha   22
3  Priya   23

In [15]:
pd.concat([df1, df2], axis=0)

    Name  Age
0   Amit   20
1  Rahul   21
0  Sneha   22
1  Priya   23

In [16]:
pd.concat([df1, df2], axis=1)

    Name  Age   Name  Age
0   Amit   20  Sneha   22
1  Rahul   21  Priya   23

# join() in Pandas

# join() is another way of combining DataFrames.

# It is mainly useful when you want to combine using the index.

In [18]:
df1 = pd.DataFrame({
    'Name': ['Amit', 'Rahul']
}, index=[1, 2])

df2 = pd.DataFrame({
    'Marks': [80, 75]
}, index=[1, 2])

In [19]:
result = df1.join(df2)

print(result)

    Name  Marks
1   Amit     80
2  Rahul     75