In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Tejas Gaikwad\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Tejas Gaikwad\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Tejas Gaikwad\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Tejas Gaikwad\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 1.2 MB/s eta 0:00:08
   --- ------------------------------------ 0.8/9.8 MB 1.2 MB/s eta 0:00:08
   ---- ----------------------------------- 1.0/9.8 MB 1.3 MB/s eta 0:00:07
   ----- ---------------------------------- 1.3/9.8 MB 1.3 MB/s eta 0:00:07
   ------- -------------------------------- 1.8/9.8 MB 1.5 MB/s eta 0:00:06
   -------- ------------------------------- 2.1/9.8 MB 1.5 MB/s eta 0:00:06
   ---------- ----------------------------- 2.6/9.8 MB 1.6 MB/s eta 0:00:05
   ----------- ---------------------------- 2.9/9.8 MB 1.6 MB/s eta 0:00:05
   ------------- -------------------------- 3.4/9.8 MB 1.7 MB/s eta 0:00:04
   -------------- ------------------------- 3.7/9.8 MB 1.7 MB/s eta 0:00:04
   ---------------- ----------------------- 3.9/9.8 MB 1.6 MB/s eta 0:00:04
   ----------------- ---------------------- 4.2/9.8 MB 1.6 MB/s eta 0:00:04
   ------------------ --------------------- 4.5/9.8 MB 1.6 MB/s eta 0:00:04
   -------------------- ------------------- 5.0/9.8 MB 1.6 MB/s eta 0:00:04
   --------------------- ------------------ 5.2/9.8 MB 1.6 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.8 MB 1.6 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.8 MB 1.6 MB/s eta 0:00:03
   ------------------------- -------------- 6.3/9.8 MB 1.6 MB/s eta 0:00:03
   --------------------------- ------------ 6.8/9.8 MB 1.6 MB/s eta 0:00:02
   ---------------------------- ----------- 7.1/9.8 MB 1.6 MB/s eta 0:00:02
   ------------------------------- -------- 7.6/9.8 MB 1.7 MB/s eta 0:00:02
   --------------------------------- ------ 8.1/9.8 MB 1.7 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.8 MB 1.8 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 1.8 MB/s  0:00:05
Installing collected packages: pandas
Successfully installed pandas-3.0.6

In [1]:
import pandas as pd
import numpy as np

In [3]:
d1 = {'e_id':[101,102,103,104,105],
      'e_name':['amol','amit','akash','avinash','atish'],
      'e_sal':[25000,17500.5,55000,82000,42200.1],
      'e_dept':['HR','HR','IT','IT','IT']}
df = pd.DataFrame(d1,index=['A','B','C','X','Y'])
df

   e_id   e_name    e_sal e_dept
A   101     amol  25000.0     HR
B   102     amit  17500.5     HR
C   103    akash  55000.0     IT
X   104  avinash  82000.0     IT
Y   105    atish  42200.1     IT

# iloc() is gives actual content of that index

In [4]:
df.iloc[3,2] #gives the value at that index

np.float64(82000.0)

In [6]:
#and we can update values also
df.iloc[3,2] = 6700
df

   e_id   e_name    e_sal e_dept
A   101     amol  25000.0     HR
B   102     amit  17500.5     HR
C   103    akash  55000.0     IT
X   104  avinash   6700.0     IT
Y   105    atish  42200.1     IT

In [7]:
df['e_sal'].mean()

np.float64(29280.120000000003)

In [9]:
df.iloc[2:,:2] #rows and column

   e_id   e_name
C   103    akash
X   104  avinash
Y   105    atish

In [10]:
print(df)

   e_id   e_name    e_sal e_dept
A   101     amol  25000.0     HR
B   102     amit  17500.5     HR
C   103    akash  55000.0     IT
X   104  avinash   6700.0     IT
Y   105    atish  42200.1     IT

# .loc() gives the row series

In [14]:
df.loc['A']

e_id          101
e_name       amol
e_sal     25000.0
e_dept         HR
Name: A, dtype: object

In [15]:
df

   e_id   e_name    e_sal e_dept
A   101     amol  25000.0     HR
B   102     amit  17500.5     HR
C   103    akash  55000.0     IT
X   104  avinash   6700.0     IT
Y   105    atish  42200.1     IT

In [18]:
df['e_dept'] == 'IT'

A    False
B    False
C     True
X     True
Y     True
Name: e_dept, dtype: bool

In [19]:
#data of employee of IT department
df[df['e_dept'] == 'IT']

   e_id   e_name    e_sal e_dept
C   103    akash  55000.0     IT
X   104  avinash   6700.0     IT
Y   105    atish  42200.1     IT

In [20]:
#we need only salary
df[df['e_dept'] == 'IT']['e_sal']

C    55000.0
X     6700.0
Y    42200.1
Name: e_sal, dtype: float64

In [21]:
#mean of salary
df[df['e_dept'] == 'IT']['e_sal'].mean()

np.float64(34633.36666666667)

#### count of employeee more than 50K salary

In [23]:
df['e_sal'] > 50000

A    False
B    False
C     True
X    False
Y    False
Name: e_sal, dtype: bool

In [24]:
sum(df['e_sal'] > 50000)

1

#### Max Salary from HR Dept

In [25]:
df['e_dept'] == 'HR'

A     True
B     True
C    False
X    False
Y    False
Name: e_dept, dtype: bool

In [26]:
df[df['e_dept'] == 'HR']['e_sal']

A    25000.0
B    17500.5
Name: e_sal, dtype: float64

In [27]:
max(df[df['e_dept'] == 'HR']['e_sal'])

25000.0

#### How many emp from "IT" dept getting less than 60K

In [28]:
df[df['e_dept'] == 'IT']['e_sal']

C    55000.0
X     6700.0
Y    42200.1
Name: e_sal, dtype: float64

In [29]:
df[df['e_dept'] == 'IT']['e_sal'] > 60000

C    False
X    False
Y    False
Name: e_sal, dtype: bool

In [30]:
sum(df[df['e_dept'] == 'IT']['e_sal'] > 60000)

0

#### Name of emp who has highest salary

In [36]:
df['e_sal'].max()

np.float64(55000.0)

In [38]:
max(df['e_sal'])

55000.0

In [39]:
df[df['e_sal'] == df['e_sal'].max()]

   e_id e_name    e_sal e_dept
C   103  akash  55000.0     IT

In [40]:
df[df['e_sal'] == df['e_sal'].max()]['e_name']

C    akash
Name: e_name, dtype: str

In [4]:
df[df['e_sal'] == df['e_sal'].max()]['e_name'].iloc[0] #if we only want the name

'avinash'

In [5]:
df[df['e_sal'] == df['e_sal'].min()]['e_name'].iloc[0]

'amit'

In [6]:
df['e_name'].min()#alphabetical order

'akash'

## Reading data from diffrent files --> Excel,sql,csv,...

In [3]:
df = pd.read_excel('stud_db.xlsx')

In [3]:
df

   Roll Name  Marks Address  Dept
0     1   qw     76    Pune     1
1     2   df     45  Mumbai     1
2     3   vc     56  Nagpur     1
3     4   bn     78    Pune     2
4     5   hj     74  Mumbai     2
5     6   yu     49  Nagpur     2
6     7   fg     68    Pune     2
7     8   tr     84  Mumbai     1

In [4]:
# 1) find avg marks from pune,mumbai,nagpur
df['Address'] == 'Pune'

0     True
1    False
2    False
3     True
4    False
5    False
6     True
7    False
Name: Address, dtype: bool

In [8]:
df[df['Address'] == 'Pune']['Marks']

0    76
3    78
6    68
Name: Marks, dtype: int64

In [9]:
df[df['Address'] == 'Pune']['Marks'].mean()

np.float64(74.0)

In [10]:
df[df['Address'] == 'Mumbai']['Marks'].mean()

np.float64(67.66666666666667)

In [11]:
df[df['Address'] == 'Nagpur']['Marks'].mean()

np.float64(52.5)

In [12]:
#2) find count of failed stdents from mumbai pass >= 50
df[df['Address'] == 'Mumbai']['Marks']

1    45
4    74
7    84
Name: Marks, dtype: int64

In [13]:
df[df['Address'] == 'Mumbai']['Marks'] <= 50

1     True
4    False
7    False
Name: Marks, dtype: bool

In [14]:
sum(df[df['Address'] == 'Mumbai']['Marks'] <= 50)

1

In [15]:
#3)find name of topper
df['Marks'].max()

np.int64(84)

In [16]:
df['Marks'].max() == df['Marks']

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
Name: Marks, dtype: bool

In [17]:
df[df['Marks'].max() == df['Marks']]

   Roll Name  Marks Address  Dept
7     8   tr     84  Mumbai     1

In [20]:
df[df['Marks'].max() == df['Marks']]['Name']

7    tr
Name: Name, dtype: str

In [21]:
df[df['Marks'].max() == df['Marks']]['Name'].iloc[0]

'tr'

In [23]:
#4)find topper marks from dept 2
df[df['Dept'] == 2]

   Roll Name  Marks Address  Dept
3     4   bn     78    Pune     2
4     5   hj     74  Mumbai     2
5     6   yu     49  Nagpur     2
6     7   fg     68    Pune     2

In [24]:
df[df['Dept'] == 2]['Marks']

3    78
4    74
5    49
6    68
Name: Marks, dtype: int64

In [39]:
df[df['Dept'] == 2]['Marks'].max()

np.int64(78)

In [26]:
print(df[df['Dept'] == 2]['Marks'].max())

78

In [4]:
#If we want to many columns so we use data in list at the end
df[df['Marks'] == df[df['Dept'] == 2]['Marks'].max()][['Name','Marks']]

  Name  Marks
3   bn     78

## Series Funtions

## 1) .unique()

In [42]:
df['Address'].unique() # Gives the unique value from data

<ArrowStringArray>
['Pune', 'Mumbai', 'Nagpur']
Length: 3, dtype: str

## 2) .nunique()

In [45]:
df['Address'].nunique() #total of unique value

3

## 3) .value_counts()

In [47]:
df['Address'].value_counts() #tells the count of unique values elements

Address
Pune      3
Mumbai    3
Nagpur    2
Name: count, dtype: int64

## 4) .appy()

In [49]:
df['Address'].apply(lambda x : x[:2]) #like we use map in list we use appy in series

0    Pu
1    Mu
2    Na
3    Pu
4    Mu
5    Na
6    Pu
7    Mu
Name: Address, dtype: str

In [51]:
df['Address'].apply(lambda x : x[0] + x[-1])

0    Pe
1    Mi
2    Nr
3    Pe
4    Mi
5    Nr
6    Pe
7    Mi
Name: Address, dtype: str

In [56]:
np.where(df['Marks'] >= 50, df['Marks'] + 5, df['Marks'] + 10)

array([81, 55, 61, 83, 79, 59, 73, 89])

In [58]:
df['Marks'].apply(lambda x : x+ 10 if x <= 50 else x + 5)

0    81
1    55
2    61
3    83
4    79
5    59
6    73
7    89
Name: Marks, dtype: int64

## DATAFRAME funtions

## 1) .groupby()

In [4]:
#groupby working in background it works like 
df.groupby('Address') #basically it is series means iterable object we can access it by the for loop

In [5]:
for i in df.groupby('Address'):
    print(i)

('Mumbai',    Roll Name  Marks Address  Dept
1     2   df     45  Mumbai     1
4     5   hj     74  Mumbai     2
7     8   tr     84  Mumbai     1)
('Nagpur',    Roll Name  Marks Address  Dept
2     3   vc     56  Nagpur     1
5     6   yu     49  Nagpur     2)
('Pune',    Roll Name  Marks Address  Dept
0     1   qw     76    Pune     1
3     4   bn     78    Pune     2
6     7   fg     68    Pune     2)

In [6]:
for i,j in df.groupby('Address'):  #here i is key that is address and the j is the values
    print(i)

Mumbai
Nagpur
Pune

In [7]:
for i,j in df.groupby('Address'):  
    print(j) #here we actualy got the values

   Roll Name  Marks Address  Dept
1     2   df     45  Mumbai     1
4     5   hj     74  Mumbai     2
7     8   tr     84  Mumbai     1
   Roll Name  Marks Address  Dept
2     3   vc     56  Nagpur     1
5     6   yu     49  Nagpur     2
   Roll Name  Marks Address  Dept
0     1   qw     76    Pune     1
3     4   bn     78    Pune     2
6     7   fg     68    Pune     2

In [8]:
# If we need the only values we use the like that
for i,j in df.groupby('Address')['Marks']:  
    print(i,j)

Mumbai 1    45
4    74
7    84
Name: Marks, dtype: int64
Nagpur 2    56
5    49
Name: Marks, dtype: int64
Pune 0    76
3    78
6    68
Name: Marks, dtype: int64

### we have to find the avg of each city ?

In [12]:
df.groupby('Address')['Marks'] #it gives the Iterable object values

In [13]:
df.groupby('Address')['Marks'].mean()

Address
Mumbai    67.666667
Nagpur    52.500000
Pune      74.000000
Name: Marks, dtype: float64

### Dept - wise topper marks

In [15]:
df.groupby('Dept')['Marks'].max()

Dept
1    84
2    78
Name: Marks, dtype: int64

In [2]:
df_stud = pd.read_excel("stud_db.xlsx")
df_stud

   Roll Name  Marks Address  Dept
0     1   qw     76    Pune     1
1     2   df     45  Mumbai     1
2     3   vc     56  Nagpur     1
3     4   bn     78    Pune     2
4     5   hj     74  Mumbai     2
5     6   yu     49  Nagpur     2
6     7   fg     68    Pune     2
7     8   tr     84  Mumbai     1

In [3]:
df_depts = pd.read_excel("stud_db.xlsx",sheet_name = "Depts")
df_depts

   dept_id          Name  HOD
0        1  Comp Science  XYZ
1        2    Statistics  PQR
2        3         Maths  MNO

# Maximum marks from name = Statistics

In [5]:
df_depts["Name"] == "Statistics"

0    False
1     True
2    False
Name: Name, dtype: bool

In [7]:
df_depts[df_depts["Name"] == "Statistics"]["dept_id"].iloc[0]

np.int64(2)

In [8]:
df_stud[df_stud["Dept"] == df_depts[df_depts["Name"] == "Statistics"]["dept_id"].iloc[0]]

   Roll Name  Marks Address  Dept
3     4   bn     78    Pune     2
4     5   hj     74  Mumbai     2
5     6   yu     49  Nagpur     2
6     7   fg     68    Pune     2

In [9]:
df_stud[df_stud["Dept"] == df_depts[df_depts["Name"] == "Statistics"]["dept_id"].iloc[0]]["Marks"].max()

np.int64(78)

In [10]:
print(df_stud[df_stud["Dept"] == df_depts[df_depts["Name"] == "Statistics"]["dept_id"].iloc[0]]["Marks"].max())

78

# Find out HOD's name of student vc

In [14]:
df_stud["Name"] == "vc"

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7    False
Name: Name, dtype: bool

In [15]:
df_stud[df_stud["Name"] == "vc"]["Dept"]

2    1
Name: Dept, dtype: int64

In [16]:
df_stud[df_stud["Name"] == "vc"]["Dept"].iloc[0]

np.int64(1)

In [18]:
df_depts["dept_id"] == df_stud[df_stud["Name"] == "vc"]["Dept"].iloc[0]

0     True
1    False
2    False
Name: dept_id, dtype: bool

In [19]:
df_depts[df_depts["dept_id"] == df_stud[df_stud["Name"] == "vc"]["Dept"].iloc[0]]["HOD"]

0    XYZ
Name: HOD, dtype: str

In [23]:
print(df_depts[df_depts["dept_id"] == df_stud[df_stud["Name"] == "vc"]["Dept"].iloc[0]]["HOD"].iloc[0])

XYZ

# **Merge Two datasets by using merge**

In [4]:
df_merge = pd.merge(df_stud,df_depts,left_on="Dept",right_on = "dept_id")
df_merge

   Roll Name_x  Marks Address  Dept  dept_id        Name_y  HOD
0     1     qw     76    Pune     1        1  Comp Science  XYZ
1     2     df     45  Mumbai     1        1  Comp Science  XYZ
2     3     vc     56  Nagpur     1        1  Comp Science  XYZ
3     4     bn     78    Pune     2        2    Statistics  PQR
4     5     hj     74  Mumbai     2        2    Statistics  PQR
5     6     yu     49  Nagpur     2        2    Statistics  PQR
6     7     fg     68    Pune     2        2    Statistics  PQR
7     8     tr     84  Mumbai     1        1  Comp Science  XYZ

# Maximum marks from name = Statistics

In [9]:
df_merge["Name_y"] == "Statistics"

0    False
1    False
2    False
3     True
4     True
5     True
6     True
7    False
Name: Name_y, dtype: bool

In [10]:
df_merge[df_merge["Name_y"] == "Statistics"]

   Roll Name_x  Marks Address  Dept  dept_id      Name_y  HOD
3     4     bn     78    Pune     2        2  Statistics  PQR
4     5     hj     74  Mumbai     2        2  Statistics  PQR
5     6     yu     49  Nagpur     2        2  Statistics  PQR
6     7     fg     68    Pune     2        2  Statistics  PQR

In [11]:
df_merge[df_merge["Name_y"] == "Statistics"]["Marks"]

3    78
4    74
5    49
6    68
Name: Marks, dtype: int64

In [12]:
df_merge[df_merge["Name_y"] == "Statistics"]["Marks"].max()

np.int64(78)

In [14]:
max(df_merge[df_merge["Name_y"] == "Statistics"]["Marks"])

78

# Find out HOD's name of student vc

In [5]:
df_merge['Name_x'] == 'vc'

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7    False
Name: Name_x, dtype: bool

In [6]:
df_merge[df_merge['Name_x'] == 'vc']

   Roll Name_x  Marks Address  Dept  dept_id        Name_y  HOD
2     3     vc     56  Nagpur     1        1  Comp Science  XYZ

In [7]:
df_merge[df_merge['Name_x'] == 'vc']['HOD']

2    XYZ
Name: HOD, dtype: str

In [8]:
df_merge[df_merge['Name_x'] == 'vc']['HOD'].iloc[0]

'XYZ'

# Joins

### 1)Inner 2)Left 3)right 4)outer join

In [15]:
pd.merge(df_stud,df_depts,left_on="Dept",right_on = "dept_id",how = "inner")

   Roll Name_x  Marks Address  Dept  dept_id        Name_y  HOD
0     1     qw     76    Pune     1        1  Comp Science  XYZ
1     2     df     45  Mumbai     1        1  Comp Science  XYZ
2     3     vc     56  Nagpur     1        1  Comp Science  XYZ
3     4     bn     78    Pune     2        2    Statistics  PQR
4     5     hj     74  Mumbai     2        2    Statistics  PQR
5     6     yu     49  Nagpur     2        2    Statistics  PQR
6     7     fg     68    Pune     2        2    Statistics  PQR
7     8     tr     84  Mumbai     1        1  Comp Science  XYZ

In [16]:
pd.merge(df_stud,df_depts,left_on="Dept",right_on = "dept_id",how = "left")

   Roll Name_x  Marks Address  Dept  dept_id        Name_y  HOD
0     1     qw     76    Pune     1        1  Comp Science  XYZ
1     2     df     45  Mumbai     1        1  Comp Science  XYZ
2     3     vc     56  Nagpur     1        1  Comp Science  XYZ
3     4     bn     78    Pune     2        2    Statistics  PQR
4     5     hj     74  Mumbai     2        2    Statistics  PQR
5     6     yu     49  Nagpur     2        2    Statistics  PQR
6     7     fg     68    Pune     2        2    Statistics  PQR
7     8     tr     84  Mumbai     1        1  Comp Science  XYZ

In [17]:
pd.merge(df_stud,df_depts,left_on="Dept",right_on = "dept_id",how = "right")

   Roll Name_x  Marks Address  Dept  dept_id        Name_y  HOD
0   1.0     qw   76.0    Pune   1.0        1  Comp Science  XYZ
1   2.0     df   45.0  Mumbai   1.0        1  Comp Science  XYZ
2   3.0     vc   56.0  Nagpur   1.0        1  Comp Science  XYZ
3   8.0     tr   84.0  Mumbai   1.0        1  Comp Science  XYZ
4   4.0     bn   78.0    Pune   2.0        2    Statistics  PQR
5   5.0     hj   74.0  Mumbai   2.0        2    Statistics  PQR
6   6.0     yu   49.0  Nagpur   2.0        2    Statistics  PQR
7   7.0     fg   68.0    Pune   2.0        2    Statistics  PQR
8   NaN    NaN    NaN     NaN   NaN        3         Maths  MNO

In [18]:
pd.merge(df_stud,df_depts,left_on="Dept",right_on = "dept_id",how = "outer") #dept coluluumn becomes the float beacuse the normally NaN is float so integer is converted in the float & others str is upper in the type castig

   Roll Name_x  Marks Address  Dept  dept_id        Name_y  HOD
0   1.0     qw   76.0    Pune   1.0        1  Comp Science  XYZ
1   2.0     df   45.0  Mumbai   1.0        1  Comp Science  XYZ
2   3.0     vc   56.0  Nagpur   1.0        1  Comp Science  XYZ
3   8.0     tr   84.0  Mumbai   1.0        1  Comp Science  XYZ
4   4.0     bn   78.0    Pune   2.0        2    Statistics  PQR
5   5.0     hj   74.0  Mumbai   2.0        2    Statistics  PQR
6   6.0     yu   49.0  Nagpur   2.0        2    Statistics  PQR
7   7.0     fg   68.0    Pune   2.0        2    Statistics  PQR
8   NaN    NaN    NaN     NaN   NaN        3         Maths  MNO

# .sorted_values("Column_name")

In [8]:
df1 = pd.merge(df_stud,df_depts,left_on="Dept",right_on = "dept_id")
df1.sort_values('Marks')

   Roll Name_x  Marks Address  Dept  dept_id        Name_y  HOD
1     2     df     45  Mumbai     1        1  Comp Science  XYZ
5     6     yu     49  Nagpur     2        2    Statistics  PQR
2     3     vc     56  Nagpur     1        1  Comp Science  XYZ
6     7     fg     68    Pune     2        2    Statistics  PQR
4     5     hj     74  Mumbai     2        2    Statistics  PQR
0     1     qw     76    Pune     1        1  Comp Science  XYZ
3     4     bn     78    Pune     2        2    Statistics  PQR
7     8     tr     84  Mumbai     1        1  Comp Science  XYZ

In [11]:
df1.sort_values('Marks',ascending = False)

   Roll Name_x  Marks Address  Dept  dept_id        Name_y  HOD
7     8     tr     84  Mumbai     1        1  Comp Science  XYZ
3     4     bn     78    Pune     2        2    Statistics  PQR
0     1     qw     76    Pune     1        1  Comp Science  XYZ
4     5     hj     74  Mumbai     2        2    Statistics  PQR
6     7     fg     68    Pune     2        2    Statistics  PQR
2     3     vc     56  Nagpur     1        1  Comp Science  XYZ
5     6     yu     49  Nagpur     2        2    Statistics  PQR
1     2     df     45  Mumbai     1        1  Comp Science  XYZ

### Merge can be done with only two dataset at a time but conacate done with many dataset
### Concate done vertically - have clumn same 
### Concate done with many datasets

In [12]:
df1 = pd.DataFrame({
    'Name': ['Amit', 'Rahul'],
    'Age': [20, 21]
})

df2 = pd.DataFrame({
    'Name': ['Sneha', 'Priya'],
    'Age': [22, 23]
})

result = pd.concat([df1, df2])

print(result)

    Name  Age
0   Amit   20
1  Rahul   21
0  Sneha   22
1  Priya   23

In [14]:
result = pd.concat([df1, df2], ignore_index=True)
print(result)

    Name  Age
0   Amit   20
1  Rahul   21
2  Sneha   22
3  Priya   23

In [15]:
pd.concat([df1, df2], axis=0)

    Name  Age
0   Amit   20
1  Rahul   21
0  Sneha   22
1  Priya   23

In [16]:
pd.concat([df1, df2], axis=1)

    Name  Age   Name  Age
0   Amit   20  Sneha   22
1  Rahul   21  Priya   23

# join() in Pandas

# join() is another way of combining DataFrames.

# It is mainly useful when you want to combine using the index.

In [18]:
df1 = pd.DataFrame({
    'Name': ['Amit', 'Rahul']
}, index=[1, 2])

df2 = pd.DataFrame({
    'Marks': [80, 75]
}, index=[1, 2])

In [19]:
result = df1.join(df2)

print(result)

    Name  Marks
1   Amit     80
2  Rahul     75

## Pivot_table

In [2]:
# import pandas as pd

sales_data = {
    "Product": ["Laptop", "Phone", "Tablet", "Laptop",
                "Phone", "Tablet", "Laptop", "Phone"],
    "City": ["Pune", "Mumbai", "Pune", "Delhi",
             "Mumbai", "Delhi", "Pune", "Pune"],
    "Sales": [65000, 25000, 18000, 72000,
              30000, 22000, 58000, 27000],
    "Quantity": [2, 5, 3, 1, 4, 2, 3, 6]
}

sales = pd.DataFrame(sales_data)

print(sales)

  Product    City  Sales  Quantity
0  Laptop    Pune  65000         2
1   Phone  Mumbai  25000         5
2  Tablet    Pune  18000         3
3  Laptop   Delhi  72000         1
4   Phone  Mumbai  30000         4
5  Tablet   Delhi  22000         2
6  Laptop    Pune  58000         3
7   Phone    Pune  27000         6

In [5]:
#sum
pivot = pd.pivot_table(
    sales,
    index = "City",
    columns = "Product",
    values = "Sales",
    aggfunc = "sum",
    fill_value = 0
)
pivot

Product  Laptop  Phone  Tablet
City
Delhi     72000      0   22000
Mumbai        0  55000       0
Pune     123000  27000   18000

In [7]:
#avg
pivot1 = pd.pivot_table(
    sales,
    index = "City",
    columns = "Product",
    values = "Sales",
    aggfunc = "mean",
    fill_value = 0
)
pivot1

Product   Laptop    Phone   Tablet
City
Delhi    72000.0      0.0  22000.0
Mumbai       0.0  27500.0      0.0
Pune     61500.0  27000.0  18000.0

In [8]:
#count
pivot = pd.pivot_table(
    sales,
    index = "City",
    columns = "Product",
    values = "Sales",
    aggfunc = "count",
    fill_value = 0
)
pivot

Product  Laptop  Phone  Tablet
City
Delhi         1      0       1
Mumbai        0      2       0
Pune          2      1       1

In [13]:
# Managers often want to see both individual totals and the overall total.
pivot = pd.pivot_table(
    sales,
    index="City",
    columns="Product",
    values="Sales",
    aggfunc="sum",
    fill_value=0,
    margins=True,
    margins_name = "Total"
)

print(pivot)

Product  Laptop  Phone  Tablet   Total
City
Delhi     72000      0   22000   94000
Mumbai        0  55000       0   55000
Pune     123000  27000   18000  168000
Total    195000  82000   40000  317000

In [11]:
pivot = pd.pivot_table(
    sales,
    index="City",
    columns="Product",
    values="Sales",
    aggfunc=["sum", "mean"]
)

print(pivot)

              sum                       mean
Product    Laptop    Phone   Tablet   Laptop    Phone   Tablet
City
Delhi     72000.0      NaN  22000.0  72000.0      NaN  22000.0
Mumbai        NaN  55000.0      NaN      NaN  27500.0      NaN
Pune     123000.0  27000.0  18000.0  61500.0  27000.0  18000.0

What is crosstab()?
A crosstab creates a frequency table showing how many times combinations of categories occur.
Use pd.crosstab() when your main question is about counts, such as:
- How many transactions involved each product in each city?
- How many students passed or failed by department?
- How many customers use each payment method?

In [14]:
result = pd.crosstab(sales["City"], sales["Product"])

print(result)

Product  Laptop  Phone  Tablet
City
Delhi         1      0       1
Mumbai        0      2       0
Pune          2      1       1

In [15]:
result = pd.crosstab(sales["City"], sales["Product"],margins = True)

print(result)

Product  Laptop  Phone  Tablet  All
City
Delhi         1      0       1    2
Mumbai        0      2       0    2
Pune          2      1       1    4
All           3      3       2    8

In [16]:
result = pd.crosstab(
    sales["City"],
    sales["Product"],
    normalize="index"
)

print(result.round(2))

Product  Laptop  Phone  Tablet
City
Delhi       0.5   0.00    0.50
Mumbai      0.0   1.00    0.00
Pune        0.5   0.25    0.25

# Pivot table
pd.pivot_table(sales, index="City", columns="Product",
               values="Sales", aggfunc="sum", fill_value=0)

# Crosstab
pd.crosstab(sales["City"], sales["Product"])

# GroupBy
sales.groupby(["City", "Product"])["Sales"].sum()

In [17]:
# 1. Create a pivot table showing total sales by city.
pd.pivot_table(sales, index="City", values="Sales", aggfunc="sum")

         Sales
City
Delhi    94000
Mumbai   55000
Pune    168000

In [19]:
# 2. Show total sales by city and product.
pd.pivot_table(sales, index="City", columns = "Product",values="Sales", aggfunc="sum")

Product    Laptop    Phone   Tablet
City
Delhi     72000.0      NaN  22000.0
Mumbai        NaN  55000.0      NaN
Pune     123000.0  27000.0  18000.0

In [20]:
# 3. Find the average sales by product.
pd.pivot_table(sales, index="Product", values="Sales", aggfunc="mean")

                Sales
Product
Laptop   65000.000000
Phone    27333.333333
Tablet   20000.000000

In [23]:
# 4. Create a pivot table with grand totals.
pivot = pd.pivot_table(sales, index="City", columns="Product", values="Sales", aggfunc="sum", fill_value=0, margins=True,margins_name="grand_total")
pivot

Product      Laptop  Phone  Tablet  grand_total
City
Delhi         72000      0   22000        94000
Mumbai            0  55000       0        55000
Pune         123000  27000   18000       168000
grand_total  195000  82000   40000       317000

In [24]:
# 5. Count records for each city and product.
pd.crosstab(sales["City"],sales["Product"])

Product  Laptop  Phone  Tablet
City
Delhi         1      0       1
Mumbai        0      2       0
Pune          2      1       1

In [25]:
# 6. Show row-wise percentages for each city and product.
pd.crosstab(sales["City"], sales["Product"], normalize="index").round(2)

Product  Laptop  Phone  Tablet
City
Delhi       0.5   0.00    0.50
Mumbai      0.0   1.00    0.00
Pune        0.5   0.25    0.25

In [26]:
# 7. Calculate total quantity by city and product.
pd.crosstab(sales["City"], sales["Product"], margins=True)

Product  Laptop  Phone  Tablet  All
City
Delhi         1      0       1    2
Mumbai        0      2       0    2
Pune          2      1       1    4
All           3      3       2    8

## DateTime

In [4]:
import pandas as pd

data = {
    "Employee": ["Rahul", "Priya", "Amit", "Sneha", "Karan"],
    "Joining_Date": [
        "2024-01-15",
        "2023-06-20",
        "2024-08-10",
        "2022-12-05",
        "2023-03-25"
    ],
    "Salary": [25000, 45000, 18000, 60000, 35000]
}
df = pd.DataFrame(data)
print(df.dtypes)

Employee          str
Joining_Date      str
Salary          int64
dtype: object

In [6]:
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"])
df.dtypes

Employee                   str
Joining_Date    datetime64[us]
Salary                   int64
dtype: object

In [7]:
df

  Employee Joining_Date  Salary
0    Rahul   2024-01-15   25000
1    Priya   2023-06-20   45000
2     Amit   2024-08-10   18000
3    Sneha   2022-12-05   60000
4    Karan   2023-03-25   35000

In [12]:
df["year"] = df["Joining_Date"].dt.year
df["month"] = df["Joining_Date"].dt.month
df["day"] = df["Joining_Date"].dt.day
df["quarter"] = df["Joining_Date"].dt.quarter
df["leap"] = df["Joining_Date"].dt.is_leap_year
df["day_name"] = df["Joining_Date"].dt.dayofweek
df["day_name"] = df["Joining_Date"].dt.day_name()
df["month_name"] = df["Joining_Date"].dt.month_name()
df

,Employee,Joining_Date,Salary,year,month,day,quarter,leap,day_name,month_name
0,Rahul,2024-01-15,25000,2024,1,15,1,True,Monday,January
1,Priya,2023-06-20,45000,2023,6,20,2,False,Tuesday,June
2,Amit,2024-08-10,18000,2024,8,10,3,True,Saturday,August
3,Sneha,2022-12-05,60000,2022,12,5,4,False,Monday,December
4,Karan,2023-03-25,35000,2023,3,25,1,False,Saturday,March

In [13]:
dates = pd.Series([
    "2024-01-15",
    "not available",
    "2024-08-10"
])

dates = pd.to_datetime(dates, errors="coerce")

print(dates) #Nat = not a time

0   2024-01-15
1          NaT
2   2024-08-10
dtype: datetime64[us]

In [14]:
print(dates.isna())
print(dates.isna().sum())

0    False
1     True
2    False
dtype: bool
1

In [19]:
# Example 1: Select dates after a particular date
res= df[df["Joining_Date"] >= "2024-01-01"]
res[["Employee","Salary"]]

  Employee  Salary
0    Rahul   25000
2     Amit   18000

In [20]:
# employees who joined in March 2023
df[(df["Joining_Date"].dt.month_name() == "March") & (df["Joining_Date"].dt.year == 2023)]

,Employee,Joining_Date,Salary,year,month,day,quarter,leap,day_name,month_name
4,Karan,2023-03-25,35000,2023,3,25,1,False,Saturday,March

In [27]:
start_date = pd.Timestamp("2003-10-16")
end_date = pd.Timestamp("2026-10-13")

difference = end_date - start_date

print(difference)
print(difference.days)

8398 days 00:00:00
8398

In [28]:
dates = pd.Series(["15-01-2024", "20-06-2023", "10-08-2024"])

dates = pd.to_datetime(dates, format="%d-%m-%Y")

print(dates)

0   2024-01-15
1   2023-06-20
2   2024-08-10
dtype: datetime64[us]

Code	Meaning	Example
%d	Day	15
%m	Month number	01
%Y	Four-digit year	2024
%y	Two-digit year	24
%H	Hour (24-hour clock)	14
%M	Minute	30
%S	Second	45

In [29]:
#fresher 1st 
sorted_df = df.sort_values("Joining_Date", ascending=False)
sorted_df

,Employee,Joining_Date,Salary,year,month,day,quarter,leap,day_name,month_name
2,Amit,2024-08-10,18000,2024,8,10,3,True,Saturday,August
0,Rahul,2024-01-15,25000,2024,1,15,1,True,Monday,January
1,Priya,2023-06-20,45000,2023,6,20,2,False,Tuesday,June
4,Karan,2023-03-25,35000,2023,3,25,1,False,Saturday,March
3,Sneha,2022-12-05,60000,2022,12,5,4,False,Monday,December

In [30]:
#monthly sales 
sales = pd.DataFrame({
    "Order_Date": [
        "2024-01-05",
        "2024-01-15",
        "2024-02-02",
        "2024-02-20",
        "2024-03-10"
    ],
    "Revenue": [1000, 2000, 1500, 2500, 3000]
})

sales["Order_Date"] = pd.to_datetime(sales["Order_Date"])

sales["Month"] = sales["Order_Date"].dt.to_period("M")

monthly_sales = sales.groupby("Month")["Revenue"].sum()

print(monthly_sales)

Month
2024-01    3000
2024-02    4000
2024-03    3000
Freq: M, Name: Revenue, dtype: int64

In [33]:
#for staing to end dates print we use the date_range
date = pd.date_range(
    start = "2026-8-15",
    end = "2026-8-19",
    freq="D"
)
date

DatetimeIndex(['2026-08-15', '2026-08-16', '2026-08-17', '2026-08-18',
               '2026-08-19'],
              dtype='datetime64[us]', freq='D')

- "D" — daily
- "h" — hourly
- "min" — every minute
- "W" — weekly
- "MS" — month start
- "ME" — month end in current Pandas versions

# .str

Task	Code
Uppercase	s.str.upper()
Lowercase	s.str.lower()
Title case	s.str.title()
Remove outer spaces	s.str.strip()
Replace text	s.str.replace("old", "new", regex=False)
Search text	s.str.contains("word", na=False)
Starts with	s.str.startswith("A", na=False)
Ends with	s.str.endswith(".com", na=False)
Split text	s.str.split()
Extract a pattern	s.str.extract(r"(\d+)")
Count characters	s.str.len()
Select first character	s.str[0]

In [36]:
sorted_df["Salary"].sort_values

<bound method Series.sort_values of 2    18000
0    25000
1    45000
4    35000
3    60000
Name: Salary, dtype: int64>

In [37]:
data = {
    "Employee": ["Rahul", "Priya", "Amit", "Sneha", "Karan", "Neha"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Salary": [45000, 60000, 35000, 75000, 45000, 25000],
    "Performance": [85, 92, 78, 95, 85, 70]
}

df = pd.DataFrame(data)

print(df)

  Employee Department  Salary  Performance
0    Rahul         IT   45000           85
1    Priya         HR   60000           92
2     Amit         IT   35000           78
3    Sneha    Finance   75000           95
4    Karan         HR   45000           85
5     Neha         IT   25000           70

In [38]:
# sort_values() — sort by column values
df.sort_values("Salary")

  Employee Department  Salary  Performance
5     Neha         IT   25000           70
2     Amit         IT   35000           78
4    Karan         HR   45000           85
0    Rahul         IT   45000           85
1    Priya         HR   60000           92
3    Sneha    Finance   75000           95

In [39]:
df.sort_values("Salary",ascending = False)

  Employee Department  Salary  Performance
3    Sneha    Finance   75000           95
1    Priya         HR   60000           92
0    Rahul         IT   45000           85
4    Karan         HR   45000           85
2     Amit         IT   35000           78
5     Neha         IT   25000           70

In [40]:
# Sort by multiple columns
result = df.sort_values(
    by=["Department", "Salary"],
    ascending=[True, False]
)

print(result[["Employee", "Department", "Salary"]])

  Employee Department  Salary
3    Sneha    Finance   75000
1    Priya         HR   60000
4    Karan         HR   45000
0    Rahul         IT   45000
2     Amit         IT   35000
5     Neha         IT   25000

In [41]:
#sorting by index
df.sort_index(ascending = False)#by default row is index

  Employee Department  Salary  Performance
5     Neha         IT   25000           70
4    Karan         HR   45000           85
3    Sneha    Finance   75000           95
2     Amit         IT   35000           78
1    Priya         HR   60000           92
0    Rahul         IT   45000           85

In [43]:
df.sort_index(ascending = False,axis = 1)

   Salary  Performance Employee Department
0   45000           85    Rahul         IT
1   60000           92    Priya         HR
2   35000           78     Amit         IT
3   75000           95    Sneha    Finance
4   45000           85    Karan         HR
5   25000           70     Neha         IT

In [44]:
df.sort_index(axis = 1)

  Department Employee  Performance  Salary
0         IT    Rahul           85   45000
1         HR    Priya           92   60000
2         IT     Amit           78   35000
3    Finance    Sneha           95   75000
4         HR    Karan           85   45000
5         IT     Neha           70   25000

In [45]:
#.rank - is basically used to rank by the sequence 1 to last
df["Salary_Rank"] = df["Salary"].rank(ascending=False)#high salary(1.0) to low(6.0)

print(df[["Employee", "Salary", "Salary_Rank"]])

  Employee  Salary  Salary_Rank
0    Rahul   45000          3.5
1    Priya   60000          2.0
2     Amit   35000          5.0
3    Sneha   75000          1.0
4    Karan   45000          3.5
5     Neha   25000          6.0

In [46]:
df["Average_Rank"] = df["Salary"].rank(
    ascending=False, method="average"
)

df["Minimum_Rank"] = df["Salary"].rank(
    ascending=False, method="min"
)

df["First_Rank"] = df["Salary"].rank(
    ascending=False, method="first"
)

In [47]:
df

,Employee,Department,Salary,Performance,Salary_Rank,Average_Rank,Minimum_Rank,First_Rank
0,Rahul,IT,45000,85,3.5,3.5,3.0,3.0
1,Priya,HR,60000,92,2.0,2.0,2.0,2.0
2,Amit,IT,35000,78,5.0,5.0,5.0,5.0
3,Sneha,Finance,75000,95,1.0,1.0,1.0,1.0
4,Karan,HR,45000,85,3.5,3.5,3.0,4.0
5,Neha,IT,25000,70,6.0,6.0,6.0,6.0

In [48]:
#top 3 emp by high sal to low
df["Salary"].nlargest(3)

3    75000
1    60000
0    45000
Name: Salary, dtype: int64

In [50]:
df.nlargest(3,"Salary")

,Employee,Department,Salary,Performance,Salary_Rank,Average_Rank,Minimum_Rank,First_Rank
3,Sneha,Finance,75000,95,1.0,1.0,1.0,1.0
1,Priya,HR,60000,92,2.0,2.0,2.0,2.0
0,Rahul,IT,45000,85,3.5,3.5,3.0,3.0

In [51]:
bottom_3 = df.nsmallest(3, "Salary")

print(bottom_3[["Employee", "Salary"]])

  Employee  Salary
5     Neha   25000
2     Amit   35000
0    Rahul   45000

When should you use each method?
Task	                          Method
Sort all employees by salary	sort_values()
Get the top five salaries	    nlargest(5, "Salary")
Get the bottom five salaries	nsmallest(5, "Salary")
Assign ranks	                rank()
Sort index labels           	sort_index()

Task	Code
Sort ascending	df.sort_values("Salary")
Sort descending	df.sort_values("Salary", ascending=False)
Sort multiple columns	df.sort_values(["Department", "Salary"])
Sort row index	df.sort_index()
Rank highest value as 1	df["Salary"].rank(ascending=False, method="min")
Get top 5	df.nlargest(5, "Salary")
Get bottom 5	df.nsmallest(5, "Salary")
Put missing values first	df.sort_values("Salary", na_position="first")
Highest value per group	df.groupby("Department")["Salary"].max()

1. What is binning?
Binning means dividing numerical values into groups or ranges called bins.
Suppose students have these marks:
25, 35, 48, 55, 67, 75, 88, 95
Instead of analyzing every mark individually, we can categorize them:
Marks range	Category
0–40	Fail
Above 40–60	Average
Above 60–80	Good
Above 80–100	Excellent
Pandas provides two important functions for this:
- pd.cut() — creates categories using the boundaries you specify.
- pd.qcut() — creates groups based on the distribution of the data, usually with approximately equal numbers of records per group.

In [52]:


data = {
    "Student": ["Amit", "Priya", "Rahul", "Sneha", "Neha", "Karan"],
    "Marks": [25, 45, 58, 72, 85, 95]
}

df = pd.DataFrame(data)

print(df)

  Student  Marks
0    Amit     25
1   Priya     45
2   Rahul     58
3   Sneha     72
4    Neha     85
5   Karan     95

In [53]:
df["Category"] = pd.cut(
    df["Marks"],
    bins=[0, 40, 60, 80, 100],
    labels=["Fail", "Average", "Good", "Excellent"],
    include_lowest=True
    
)

print(df)

  Student  Marks   Category
0    Amit     25       Fail
1   Priya     45    Average
2   Rahul     58    Average
3   Sneha     72       Good
4    Neha     85  Excellent
5   Karan     95  Excellent

In [54]:
marks = pd.Series([40, 41, 60, 61])

print(pd.cut(
    marks,
    bins=[0, 40, 60, 80],
    right=False #include 0 exclude 80
))

0    [40, 60)
1    [40, 60)
2    [60, 80)
3    [60, 80)
dtype: category
Categories (3, interval[int64, left]): [[0, 40) < [40, 60) < [60, 80)]

In [55]:
import pandas as pd

sales = pd.Series([10, 20, 30, 40, 50, 60, 70, 80])

sales_group = pd.qcut(
    sales,
    q=4,#equal divide
    labels=["Q1", "Q2", "Q3", "Q4"]
)

result = pd.DataFrame({
    "Sales": sales,
    "Sales_Group": sales_group
})

print(result)

   Sales Sales_Group
0     10          Q1
1     20          Q1
2     30          Q2
3     40          Q2
4     50          Q3
5     60          Q3
6     70          Q4
7     80          Q4