In [1]:
import pandas as pd
sales_data = {
    "Product": ["Laptop", "Phone", "Tablet", "Laptop", "Phone", "Tablet", "Laptop", "Phone"],
    "City": ["Pune", "Mumbai", "Pune", "Delhi", "Mumbai", "Delhi", "Pune", "Pune"],
    "Sales": [65000, 25000, 18000, 72000, 30000, 22000, 58000, 27000],
    "Quantity": [2, 5, 3, 1, 4, 2, 3, 6]
}

sales = pd.DataFrame(sales_data)
sales

  Product    City  Sales  Quantity
0  Laptop    Pune  65000         2
1   Phone  Mumbai  25000         5
2  Tablet    Pune  18000         3
3  Laptop   Delhi  72000         1
4   Phone  Mumbai  30000         4
5  Tablet   Delhi  22000         2
6  Laptop    Pune  58000         3
7   Phone    Pune  27000         6

In [7]:
# Question 1: Total sales by city
s = sales.groupby("City")["Sales"].sum()
s

City
Delhi      94000
Mumbai     55000
Pune      168000
Name: Sales, dtype: int64

In [17]:
print(s[s.max() == s])

City
Pune    168000
Name: Sales, dtype: int64

In [18]:
# Question 2: Total quantity sold for each product
sales.groupby("Product")["Quantity"].sum()

Product
Laptop     6
Phone     15
Tablet     5
Name: Quantity, dtype: int64

In [23]:
sales.groupby("Product")["Quantity"].sum().idxmax()

'Phone'

In [25]:
# Question 3: Average sales by product
sales.groupby("Product")["Sales"].mean()

Product
Laptop    65000.000000
Phone     27333.333333
Tablet    20000.000000
Name: Sales, dtype: float64

In [27]:
# Question 4: Total sales for each product in each city
sales.groupby(["Product","City"])["Sales"].sum()

Product  City
Laptop   Delhi      72000
         Pune      123000
Phone    Mumbai     55000
         Pune       27000
Tablet   Delhi      22000
         Pune       18000
Name: Sales, dtype: int64

In [28]:
# How do you calculate total sales by city, from highest to lowest?
sales.groupby("City")["Sales"].sum().sort_values(ascending = False)

City
Pune      168000
Delhi      94000
Mumbai     55000
Name: Sales, dtype: int64

In [30]:
# Q7. How do you calculate multiple statistics together?
sales.groupby("City")["Sales"].agg(["mean","median","max"])

           mean   median    max
City
Delhi   47000.0  47000.0  72000
Mumbai  27500.0  27500.0  30000
Pune    42000.0  42500.0  65000

In [31]:
# import pandas as pd

data = {
    "Name": ["Tejas", "Rahul", "Priya", "Amit", "Neha", "Karan", "Sneha", "Om"],
    "Department": ["IT", "HR", "IT", "Sales", "HR", "Sales", "IT", "HR"],
    "City": ["Pune", "Mumbai", "Pune", "Nashik", "Mumbai", "Pune", "Nashik", "Mumbai"],
    "Salary": [30000, 25000, 40000, 28000, 32000, 35000, 45000, 27000],
    "Age": [22, 24, 23, 25, 26, 24, 22, 25]
}

df = pd.DataFrame(data)

print(df)

    Name Department    City  Salary  Age
0  Tejas         IT    Pune   30000   22
1  Rahul         HR  Mumbai   25000   24
2  Priya         IT    Pune   40000   23
3   Amit      Sales  Nashik   28000   25
4   Neha         HR  Mumbai   32000   26
5  Karan      Sales    Pune   35000   24
6  Sneha         IT  Nashik   45000   22
7     Om         HR  Mumbai   27000   25

In [33]:
# Calculate the average age for each department.
df.groupby("Department")["Age"].mean()

Department
HR       25.000000
IT       22.333333
Sales    24.500000
Name: Age, dtype: float64

In [34]:
# Calculate the total salary for each city.
df.groupby("City")["Salary"].sum()

City
Mumbai     84000
Nashik     73000
Pune      105000
Name: Salary, dtype: int64

In [35]:
# Find the highest salary in each department.
df.groupby("Department")["Salary"].max()

Department
HR       32000
IT       45000
Sales    35000
Name: Salary, dtype: int64

In [37]:
# Count employees in each city.
df.groupby("City")["Name"].count()

City
Mumbai    3
Nashik    2
Pune      3
Name: Name, dtype: int64

In [38]:
df.groupby("City").size()

City
Mumbai    3
Nashik    2
Pune      3
dtype: int64

In [40]:
# Calculate average salary and maximum salary by department.
df.groupby("Department")["Salary"].agg(["mean","max"])

                    mean    max
Department
HR          28000.000000  32000
IT          38333.333333  45000
Sales       31500.000000  35000

In [42]:
# Find total salary by department and city.
df.groupby(["Department","City"])["Salary"].sum().reset_index

<bound method Series.reset_index of Department  City
HR          Mumbai    84000
IT          Nashik    45000
            Pune      70000
Sales       Nashik    28000
            Pune      35000
Name: Salary, dtype: int64>

In [43]:
# Sort departments by total salary, highest first.
df.groupby("Department")["Salary"].sum().sort_values(ascending = False)

Department
IT       115000
HR        84000
Sales     63000
Name: Salary, dtype: int64

In [47]:
# Display all employees in departments whose average salary is above ₹30,000.
df.groupby("Department").filter(lambda group: group["Salary"].mean() > 30000)

    Name Department    City  Salary  Age
0  Tejas         IT    Pune   30000   22
2  Priya         IT    Pune   40000   23
3   Amit      Sales  Nashik   28000   25
5  Karan      Sales    Pune   35000   24
6  Sneha         IT  Nashik   45000   22

In [58]:
df

    Name Department    City  Salary  Age
0  Tejas         IT    Pune   30000   22
1  Rahul         HR  Mumbai   25000   24
2  Priya         IT    Pune   40000   23
3   Amit      Sales  Nashik   28000   25
4   Neha         HR  Mumbai   32000   26
5  Karan      Sales    Pune   35000   24
6  Sneha         IT  Nashik   45000   22
7     Om         HR  Mumbai   27000   25

In [59]:
customers = pd.DataFrame({
    "CustomerID": [1, 2, 3, 4],
    "CustomerName": ["Tejas", "Rahul", "Priya", "Amit"],
    "City": ["Pune", "Mumbai", "Nashik", "Pune"]
})

orders = pd.DataFrame({
    "OrderID": [501, 502, 503, 504],
    "CustomerID": [1, 2, 1, 5],
    "Amount": [1500, 2500, 3000, 1200]
})

In [61]:
# Task 1: Find orders with customer details
pd.merge(customers,orders,on ="CustomerID",how= "inner")

   CustomerID CustomerName    City  OrderID  Amount
0           1        Tejas    Pune      501    1500
1           1        Tejas    Pune      503    3000
2           2        Rahul  Mumbai      502    2500

In [62]:
# Task 2: Keep all customers, including those without orders
pd.merge(customers,orders,on ="CustomerID",how= "left")

   CustomerID CustomerName    City  OrderID  Amount
0           1        Tejas    Pune    501.0  1500.0
1           1        Tejas    Pune    503.0  3000.0
2           2        Rahul  Mumbai    502.0  2500.0
3           3        Priya  Nashik      NaN     NaN
4           4         Amit    Pune      NaN     NaN

In [66]:
# Task 3: Calculate total order amount by customer
res = pd.merge(customers,orders,on ="CustomerID",how= "inner")

In [67]:
res.groupby("CustomerID")["Amount"].sum()

CustomerID
1    4500
2    2500
Name: Amount, dtype: int64

In [68]:
# How do you stack two DataFrames vertically?
pd.concat([customers, orders], axis=0, ignore_index=True)

   CustomerID CustomerName    City  OrderID  Amount
0           1        Tejas    Pune      NaN     NaN
1           2        Rahul  Mumbai      NaN     NaN
2           3        Priya  Nashik      NaN     NaN
3           4         Amit    Pune      NaN     NaN
4           1          NaN     NaN    501.0  1500.0
5           2          NaN     NaN    502.0  2500.0
6           1          NaN     NaN    503.0  3000.0
7           5          NaN     NaN    504.0  1200.0

In [69]:
pd.concat([customers, orders], axis=1, ignore_index=True)

   0      1       2    3  4     5
0  1  Tejas    Pune  501  1  1500
1  2  Rahul  Mumbai  502  2  2500
2  3  Priya  Nashik  503  1  3000
3  4   Amit    Pune  504  5  1200